/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedStandingsRouteImport } from './routes/_authenticated/standings'
import { Route as AuthenticatedSponsorsRouteImport } from './routes/_authenticated/sponsors'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRefereesRouteImport } from './routes/_authenticated/referees'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChampionshipsRouteImport } from './routes/_authenticated/championships'
import { Route as AuthenticatedAthletesRouteImport } from './routes/_authenticated/athletes'
import { Route as AuthenticatedChampionshipsIdRouteImport } from './routes/_authenticated/championships_.$id'
import { Route as AuthenticatedChampionshipsIdIndexRouteImport } from './routes/_authenticated/championships_.$id.index'
import { Route as AuthenticatedChampionshipsIdTeamsRouteImport } from './routes/_authenticated/championships_.$id.teams'
import { Route as AuthenticatedChampionshipsIdAthletesRouteImport } from './routes/_authenticated/championships_.$id.athletes'
import { Route as AuthenticatedChampionshipsIdTeamsIndexRouteImport } from './routes/_authenticated/championships_.$id.teams.index'
import { Route as AuthenticatedChampionshipsIdTeamsNewRouteImport } from './routes/_authenticated/championships_.$id.teams.new'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.index'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.staff'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.roster'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.responsibles'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.edit'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.athletes.new'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.athletes.$athleteId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStandingsRoute = AuthenticatedStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSponsorsRoute = AuthenticatedSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRefereesRoute = AuthenticatedRefereesRouteImport.update({
  id: '/referees',
  path: '/referees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChampionshipsRoute =
  AuthenticatedChampionshipsRouteImport.update({
    id: '/championships',
    path: '/championships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthletesRoute = AuthenticatedAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChampionshipsIdRoute =
  AuthenticatedChampionshipsIdRouteImport.update({
    id: '/championships_/$id',
    path: '/championships/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChampionshipsIdIndexRoute =
  AuthenticatedChampionshipsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsRoute =
  AuthenticatedChampionshipsIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdAthletesRoute =
  AuthenticatedChampionshipsIdAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsIndexRoute =
  AuthenticatedChampionshipsIdTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsNewRoute =
  AuthenticatedChampionshipsIdTeamsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport.update({
    id: '/responsibles',
    path: '/responsibles',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdEditRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport.update({
    id: '/athletes/new',
    path: '/athletes/new',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport.update({
    id: '/athletes/$athleteId',
    path: '/athletes/$athleteId',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/athletes': typeof AuthenticatedAthletesRoute
  '/championships': typeof AuthenticatedChampionshipsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/media': typeof AuthenticatedMediaRoute
  '/referees': typeof AuthenticatedRefereesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sponsors': typeof AuthenticatedSponsorsRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/c/$slug': typeof CSlugRoute
  '/championships/$id': typeof AuthenticatedChampionshipsIdRouteWithChildren
  '/championships/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/championships/$id/teams': typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  '/championships/$id/': typeof AuthenticatedChampionshipsIdIndexRoute
  '/championships/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  '/championships/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/championships/$id/teams/': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/championships/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/championships/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/championships/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/championships/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/championships/$id/teams/$teamId/': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/championships/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/championships/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/athletes': typeof AuthenticatedAthletesRoute
  '/championships': typeof AuthenticatedChampionshipsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/media': typeof AuthenticatedMediaRoute
  '/referees': typeof AuthenticatedRefereesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sponsors': typeof AuthenticatedSponsorsRoute
  '/standings': typeof AuthenticatedStandingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/c/$slug': typeof CSlugRoute
  '/championships/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/championships/$id': typeof AuthenticatedChampionshipsIdIndexRoute
  '/championships/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/championships/$id/teams': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/championships/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/championships/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/championships/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/championships/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/championships/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/championships/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/championships/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/athletes': typeof AuthenticatedAthletesRoute
  '/_authenticated/championships': typeof AuthenticatedChampionshipsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/referees': typeof AuthenticatedRefereesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sponsors': typeof AuthenticatedSponsorsRoute
  '/_authenticated/standings': typeof AuthenticatedStandingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/c/$slug': typeof CSlugRoute
  '/_authenticated/championships_/$id': typeof AuthenticatedChampionshipsIdRouteWithChildren
  '/_authenticated/championships_/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/_authenticated/championships_/$id/teams': typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  '/_authenticated/championships_/$id/': typeof AuthenticatedChampionshipsIdIndexRoute
  '/_authenticated/championships_/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  '/_authenticated/championships_/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/_authenticated/championships_/$id/teams/': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/_authenticated/championships_/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/_authenticated/championships_/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/_authenticated/championships_/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/_authenticated/championships_/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/_authenticated/championships_/$id/teams/$teamId/': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/_authenticated/championships_/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/athletes'
    | '/championships'
    | '/dashboard'
    | '/finance'
    | '/matches'
    | '/media'
    | '/referees'
    | '/settings'
    | '/sponsors'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/c/$slug'
    | '/championships/$id'
    | '/championships/$id/athletes'
    | '/championships/$id/teams'
    | '/championships/$id/'
    | '/championships/$id/teams/$teamId'
    | '/championships/$id/teams/new'
    | '/championships/$id/teams/'
    | '/championships/$id/teams/$teamId/edit'
    | '/championships/$id/teams/$teamId/responsibles'
    | '/championships/$id/teams/$teamId/roster'
    | '/championships/$id/teams/$teamId/staff'
    | '/championships/$id/teams/$teamId/'
    | '/championships/$id/teams/$teamId/athletes/$athleteId'
    | '/championships/$id/teams/$teamId/athletes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/athletes'
    | '/championships'
    | '/dashboard'
    | '/finance'
    | '/matches'
    | '/media'
    | '/referees'
    | '/settings'
    | '/sponsors'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/c/$slug'
    | '/championships/$id/athletes'
    | '/championships/$id'
    | '/championships/$id/teams/new'
    | '/championships/$id/teams'
    | '/championships/$id/teams/$teamId/edit'
    | '/championships/$id/teams/$teamId/responsibles'
    | '/championships/$id/teams/$teamId/roster'
    | '/championships/$id/teams/$teamId/staff'
    | '/championships/$id/teams/$teamId'
    | '/championships/$id/teams/$teamId/athletes/$athleteId'
    | '/championships/$id/teams/$teamId/athletes/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/athletes'
    | '/_authenticated/championships'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/matches'
    | '/_authenticated/media'
    | '/_authenticated/referees'
    | '/_authenticated/settings'
    | '/_authenticated/sponsors'
    | '/_authenticated/standings'
    | '/_authenticated/stats'
    | '/_authenticated/teams'
    | '/c/$slug'
    | '/_authenticated/championships_/$id'
    | '/_authenticated/championships_/$id/athletes'
    | '/_authenticated/championships_/$id/teams'
    | '/_authenticated/championships_/$id/'
    | '/_authenticated/championships_/$id/teams/$teamId'
    | '/_authenticated/championships_/$id/teams/new'
    | '/_authenticated/championships_/$id/teams/'
    | '/_authenticated/championships_/$id/teams/$teamId/edit'
    | '/_authenticated/championships_/$id/teams/$teamId/responsibles'
    | '/_authenticated/championships_/$id/teams/$teamId/roster'
    | '/_authenticated/championships_/$id/teams/$teamId/staff'
    | '/_authenticated/championships_/$id/teams/$teamId/'
    | '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId'
    | '/_authenticated/championships_/$id/teams/$teamId/athletes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/standings': {
      id: '/_authenticated/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedStandingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sponsors': {
      id: '/_authenticated/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AuthenticatedSponsorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referees': {
      id: '/_authenticated/referees'
      path: '/referees'
      fullPath: '/referees'
      preLoaderRoute: typeof AuthenticatedRefereesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/championships': {
      id: '/_authenticated/championships'
      path: '/championships'
      fullPath: '/championships'
      preLoaderRoute: typeof AuthenticatedChampionshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletes': {
      id: '/_authenticated/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AuthenticatedAthletesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/championships_/$id': {
      id: '/_authenticated/championships_/$id'
      path: '/championships/$id'
      fullPath: '/championships/$id'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/championships_/$id/': {
      id: '/_authenticated/championships_/$id/'
      path: '/'
      fullPath: '/championships/$id/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/teams': {
      id: '/_authenticated/championships_/$id/teams'
      path: '/teams'
      fullPath: '/championships/$id/teams'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/athletes': {
      id: '/_authenticated/championships_/$id/athletes'
      path: '/athletes'
      fullPath: '/championships/$id/athletes'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdAthletesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/teams/': {
      id: '/_authenticated/championships_/$id/teams/'
      path: '/'
      fullPath: '/championships/$id/teams/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/new': {
      id: '/_authenticated/championships_/$id/teams/new'
      path: '/new'
      fullPath: '/championships/$id/teams/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsNewRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId': {
      id: '/_authenticated/championships_/$id/teams/$teamId'
      path: '/$teamId'
      fullPath: '/championships/$id/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/': {
      id: '/_authenticated/championships_/$id/teams/$teamId/'
      path: '/'
      fullPath: '/championships/$id/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/staff': {
      id: '/_authenticated/championships_/$id/teams/$teamId/staff'
      path: '/staff'
      fullPath: '/championships/$id/teams/$teamId/staff'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/roster': {
      id: '/_authenticated/championships_/$id/teams/$teamId/roster'
      path: '/roster'
      fullPath: '/championships/$id/teams/$teamId/roster'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/responsibles': {
      id: '/_authenticated/championships_/$id/teams/$teamId/responsibles'
      path: '/responsibles'
      fullPath: '/championships/$id/teams/$teamId/responsibles'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/edit': {
      id: '/_authenticated/championships_/$id/teams/$teamId/edit'
      path: '/edit'
      fullPath: '/championships/$id/teams/$teamId/edit'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/athletes/new': {
      id: '/_authenticated/championships_/$id/teams/$teamId/athletes/new'
      path: '/athletes/new'
      fullPath: '/championships/$id/teams/$teamId/athletes/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId': {
      id: '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/championships/$id/teams/$teamId/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
  }
}

interface AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren {
  AuthenticatedChampionshipsIdTeamsTeamIdEditRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}

const AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren: AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren =
  {
    AuthenticatedChampionshipsIdTeamsTeamIdEditRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdEditRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute,
  }

const AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren =
  AuthenticatedChampionshipsIdTeamsTeamIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren,
  )

interface AuthenticatedChampionshipsIdTeamsRouteChildren {
  AuthenticatedChampionshipsIdTeamsTeamIdRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  AuthenticatedChampionshipsIdTeamsNewRoute: typeof AuthenticatedChampionshipsIdTeamsNewRoute
  AuthenticatedChampionshipsIdTeamsIndexRoute: typeof AuthenticatedChampionshipsIdTeamsIndexRoute
}

const AuthenticatedChampionshipsIdTeamsRouteChildren: AuthenticatedChampionshipsIdTeamsRouteChildren =
  {
    AuthenticatedChampionshipsIdTeamsTeamIdRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren,
    AuthenticatedChampionshipsIdTeamsNewRoute:
      AuthenticatedChampionshipsIdTeamsNewRoute,
    AuthenticatedChampionshipsIdTeamsIndexRoute:
      AuthenticatedChampionshipsIdTeamsIndexRoute,
  }

const AuthenticatedChampionshipsIdTeamsRouteWithChildren =
  AuthenticatedChampionshipsIdTeamsRoute._addFileChildren(
    AuthenticatedChampionshipsIdTeamsRouteChildren,
  )

interface AuthenticatedChampionshipsIdRouteChildren {
  AuthenticatedChampionshipsIdAthletesRoute: typeof AuthenticatedChampionshipsIdAthletesRoute
  AuthenticatedChampionshipsIdTeamsRoute: typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  AuthenticatedChampionshipsIdIndexRoute: typeof AuthenticatedChampionshipsIdIndexRoute
}

const AuthenticatedChampionshipsIdRouteChildren: AuthenticatedChampionshipsIdRouteChildren =
  {
    AuthenticatedChampionshipsIdAthletesRoute:
      AuthenticatedChampionshipsIdAthletesRoute,
    AuthenticatedChampionshipsIdTeamsRoute:
      AuthenticatedChampionshipsIdTeamsRouteWithChildren,
    AuthenticatedChampionshipsIdIndexRoute:
      AuthenticatedChampionshipsIdIndexRoute,
  }

const AuthenticatedChampionshipsIdRouteWithChildren =
  AuthenticatedChampionshipsIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAthletesRoute: typeof AuthenticatedAthletesRoute
  AuthenticatedChampionshipsRoute: typeof AuthenticatedChampionshipsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedRefereesRoute: typeof AuthenticatedRefereesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSponsorsRoute: typeof AuthenticatedSponsorsRoute
  AuthenticatedStandingsRoute: typeof AuthenticatedStandingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedChampionshipsIdRoute: typeof AuthenticatedChampionshipsIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAthletesRoute: AuthenticatedAthletesRoute,
  AuthenticatedChampionshipsRoute: AuthenticatedChampionshipsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedRefereesRoute: AuthenticatedRefereesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSponsorsRoute: AuthenticatedSponsorsRoute,
  AuthenticatedStandingsRoute: AuthenticatedStandingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedChampionshipsIdRoute:
    AuthenticatedChampionshipsIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
