/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SystemAdminRouteRouteImport } from './routes/system-admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemAdminIndexRouteImport } from './routes/system-admin/index'
import { Route as TeamAccessSessionRouteImport } from './routes/team-access.session'
import { Route as TeamAccessTokenRouteImport } from './routes/team-access.$token'
import { Route as SystemAdminUsuariosRouteImport } from './routes/system-admin/usuarios'
import { Route as SystemAdminSuporteRouteImport } from './routes/system-admin/suporte'
import { Route as SystemAdminOrganizacoesRouteImport } from './routes/system-admin/organizacoes'
import { Route as SystemAdminConfiguracoesRouteImport } from './routes/system-admin/configuracoes'
import { Route as SystemAdminCampeonatosRouteImport } from './routes/system-admin/campeonatos'
import { Route as SystemAdminAuditoriaRouteImport } from './routes/system-admin/auditoria'
import { Route as SystemAdminAssinaturasRouteImport } from './routes/system-admin/assinaturas'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedOrganizerRouteRouteImport } from './routes/_authenticated/_organizer/route'
import { Route as AuthenticatedChampionshipsIdRouteImport } from './routes/_authenticated/championships_.$id'
import { Route as AuthenticatedOrganizerTeamsRouteImport } from './routes/_authenticated/_organizer/teams'
import { Route as AuthenticatedOrganizerStatsRouteImport } from './routes/_authenticated/_organizer/stats'
import { Route as AuthenticatedOrganizerStandingsRouteImport } from './routes/_authenticated/_organizer/standings'
import { Route as AuthenticatedOrganizerSponsorsRouteImport } from './routes/_authenticated/_organizer/sponsors'
import { Route as AuthenticatedOrganizerSettingsRouteImport } from './routes/_authenticated/_organizer/settings'
import { Route as AuthenticatedOrganizerRefereesRouteImport } from './routes/_authenticated/_organizer/referees'
import { Route as AuthenticatedOrganizerMediaRouteImport } from './routes/_authenticated/_organizer/media'
import { Route as AuthenticatedOrganizerMatchesRouteImport } from './routes/_authenticated/_organizer/matches'
import { Route as AuthenticatedOrganizerFinanceRouteImport } from './routes/_authenticated/_organizer/finance'
import { Route as AuthenticatedOrganizerDashboardRouteImport } from './routes/_authenticated/_organizer/dashboard'
import { Route as AuthenticatedOrganizerChampionshipsRouteImport } from './routes/_authenticated/_organizer/championships'
import { Route as AuthenticatedOrganizerAthletesRouteImport } from './routes/_authenticated/_organizer/athletes'
import { Route as AuthenticatedChampionshipsIdIndexRouteImport } from './routes/_authenticated/championships_.$id.index'
import { Route as AuthenticatedOrganizerTeamsIndexRouteImport } from './routes/_authenticated/_organizer/teams.index'
import { Route as AuthenticatedOrganizerSettingsIndexRouteImport } from './routes/_authenticated/_organizer/settings.index'
import { Route as AuthenticatedOrganizerAthletesIndexRouteImport } from './routes/_authenticated/_organizer/athletes.index'
import { Route as ApiBillingInfinitepayWebhookRouteImport } from './routes/api.billing.infinitepay.webhook'
import { Route as AuthenticatedChampionshipsIdTeamsRouteImport } from './routes/_authenticated/championships_.$id.teams'
import { Route as AuthenticatedChampionshipsIdStructureRouteImport } from './routes/_authenticated/championships_.$id.structure'
import { Route as AuthenticatedChampionshipsIdStatsRouteImport } from './routes/_authenticated/championships_.$id.stats'
import { Route as AuthenticatedChampionshipsIdStandingsRouteImport } from './routes/_authenticated/championships_.$id.standings'
import { Route as AuthenticatedChampionshipsIdSponsorsRouteImport } from './routes/_authenticated/championships_.$id.sponsors'
import { Route as AuthenticatedChampionshipsIdSettingsRouteImport } from './routes/_authenticated/championships_.$id.settings'
import { Route as AuthenticatedChampionshipsIdSanctionsRouteImport } from './routes/_authenticated/championships_.$id.sanctions'
import { Route as AuthenticatedChampionshipsIdRefereesRouteImport } from './routes/_authenticated/championships_.$id.referees'
import { Route as AuthenticatedChampionshipsIdPublicPageRouteImport } from './routes/_authenticated/championships_.$id.public-page'
import { Route as AuthenticatedChampionshipsIdMediaRouteImport } from './routes/_authenticated/championships_.$id.media'
import { Route as AuthenticatedChampionshipsIdMatchesRouteImport } from './routes/_authenticated/championships_.$id.matches'
import { Route as AuthenticatedChampionshipsIdFinanceRouteImport } from './routes/_authenticated/championships_.$id.finance'
import { Route as AuthenticatedChampionshipsIdConfigurationRouteImport } from './routes/_authenticated/championships_.$id.configuration'
import { Route as AuthenticatedChampionshipsIdAuditRouteImport } from './routes/_authenticated/championships_.$id.audit'
import { Route as AuthenticatedChampionshipsIdAthletesRouteImport } from './routes/_authenticated/championships_.$id.athletes'
import { Route as AuthenticatedOrganizerTeamsTeamIdRouteImport } from './routes/_authenticated/_organizer/teams.$teamId'
import { Route as AuthenticatedOrganizerSettingsUsersRouteImport } from './routes/_authenticated/_organizer/settings.users'
import { Route as AuthenticatedOrganizerSettingsSubscriptionRouteImport } from './routes/_authenticated/_organizer/settings.subscription'
import { Route as AuthenticatedOrganizerSettingsPublicPageRouteImport } from './routes/_authenticated/_organizer/settings.public-page'
import { Route as AuthenticatedOrganizerSettingsOrganizationRouteImport } from './routes/_authenticated/_organizer/settings.organization'
import { Route as AuthenticatedOrganizerSettingsNotificationsRouteImport } from './routes/_authenticated/_organizer/settings.notifications'
import { Route as AuthenticatedOrganizerAthletesAthleteIdRouteImport } from './routes/_authenticated/_organizer/athletes.$athleteId'
import { Route as AuthenticatedChampionshipsIdTeamsIndexRouteImport } from './routes/_authenticated/championships_.$id.teams.index'
import { Route as AuthenticatedChampionshipsIdTeamsNewRouteImport } from './routes/_authenticated/championships_.$id.teams.new'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId'
import { Route as AuthenticatedChampionshipsIdMatchesMatchIdRouteImport } from './routes/_authenticated/championships_.$id.matches.$matchId'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.index'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.staff'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.roster'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.responsibles'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.edit'
import { Route as AuthenticatedChampionshipsIdStructureStagesStageIdRouteImport } from './routes/_authenticated/championships_.$id.structure.stages.$stageId'
import { Route as AuthenticatedChampionshipsIdMatchesMatchIdReportRouteImport } from './routes/_authenticated/championships_.$id.matches.$matchId.report'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.athletes.new'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.athletes.$athleteId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminRouteRoute = SystemAdminRouteRouteImport.update({
  id: '/system-admin',
  path: '/system-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminIndexRoute = SystemAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const TeamAccessSessionRoute = TeamAccessSessionRouteImport.update({
  id: '/team-access/session',
  path: '/team-access/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAccessTokenRoute = TeamAccessTokenRouteImport.update({
  id: '/team-access/$token',
  path: '/team-access/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminUsuariosRoute = SystemAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const SystemAdminSuporteRoute = SystemAdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const SystemAdminOrganizacoesRoute = SystemAdminOrganizacoesRouteImport.update({
  id: '/organizacoes',
  path: '/organizacoes',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const SystemAdminConfiguracoesRoute =
  SystemAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => SystemAdminRouteRoute,
  } as any)
const SystemAdminCampeonatosRoute = SystemAdminCampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const SystemAdminAuditoriaRoute = SystemAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const SystemAdminAssinaturasRoute = SystemAdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizerRouteRoute =
  AuthenticatedOrganizerRouteRouteImport.update({
    id: '/_organizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChampionshipsIdRoute =
  AuthenticatedChampionshipsIdRouteImport.update({
    id: '/championships_/$id',
    path: '/championships/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerTeamsRoute =
  AuthenticatedOrganizerTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerStatsRoute =
  AuthenticatedOrganizerStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerStandingsRoute =
  AuthenticatedOrganizerStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerSponsorsRoute =
  AuthenticatedOrganizerSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerSettingsRoute =
  AuthenticatedOrganizerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerRefereesRoute =
  AuthenticatedOrganizerRefereesRouteImport.update({
    id: '/referees',
    path: '/referees',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerMediaRoute =
  AuthenticatedOrganizerMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerMatchesRoute =
  AuthenticatedOrganizerMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerFinanceRoute =
  AuthenticatedOrganizerFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerDashboardRoute =
  AuthenticatedOrganizerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerChampionshipsRoute =
  AuthenticatedOrganizerChampionshipsRouteImport.update({
    id: '/championships',
    path: '/championships',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerAthletesRoute =
  AuthenticatedOrganizerAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedChampionshipsIdIndexRoute =
  AuthenticatedChampionshipsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedOrganizerTeamsIndexRoute =
  AuthenticatedOrganizerTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizerTeamsRoute,
  } as any)
const AuthenticatedOrganizerSettingsIndexRoute =
  AuthenticatedOrganizerSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizerSettingsRoute,
  } as any)
const AuthenticatedOrganizerAthletesIndexRoute =
  AuthenticatedOrganizerAthletesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizerAthletesRoute,
  } as any)
const ApiBillingInfinitepayWebhookRoute =
  ApiBillingInfinitepayWebhookRouteImport.update({
    id: '/api/billing/infinitepay/webhook',
    path: '/api/billing/infinitepay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChampionshipsIdTeamsRoute =
  AuthenticatedChampionshipsIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdStructureRoute =
  AuthenticatedChampionshipsIdStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdStatsRoute =
  AuthenticatedChampionshipsIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdStandingsRoute =
  AuthenticatedChampionshipsIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdSponsorsRoute =
  AuthenticatedChampionshipsIdSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdSettingsRoute =
  AuthenticatedChampionshipsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdSanctionsRoute =
  AuthenticatedChampionshipsIdSanctionsRouteImport.update({
    id: '/sanctions',
    path: '/sanctions',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdRefereesRoute =
  AuthenticatedChampionshipsIdRefereesRouteImport.update({
    id: '/referees',
    path: '/referees',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdPublicPageRoute =
  AuthenticatedChampionshipsIdPublicPageRouteImport.update({
    id: '/public-page',
    path: '/public-page',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdMediaRoute =
  AuthenticatedChampionshipsIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdMatchesRoute =
  AuthenticatedChampionshipsIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdFinanceRoute =
  AuthenticatedChampionshipsIdFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdConfigurationRoute =
  AuthenticatedChampionshipsIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdAuditRoute =
  AuthenticatedChampionshipsIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdAthletesRoute =
  AuthenticatedChampionshipsIdAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedOrganizerTeamsTeamIdRoute =
  AuthenticatedOrganizerTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedOrganizerTeamsRoute,
  } as any)
const AuthenticatedOrganizerSettingsUsersRoute =
  AuthenticatedOrganizerSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedOrganizerSettingsRoute,
  } as any)
const AuthenticatedOrganizerSettingsSubscriptionRoute =
  AuthenticatedOrganizerSettingsSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedOrganizerSettingsRoute,
  } as any)
const AuthenticatedOrganizerSettingsPublicPageRoute =
  AuthenticatedOrganizerSettingsPublicPageRouteImport.update({
    id: '/public-page',
    path: '/public-page',
    getParentRoute: () => AuthenticatedOrganizerSettingsRoute,
  } as any)
const AuthenticatedOrganizerSettingsOrganizationRoute =
  AuthenticatedOrganizerSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedOrganizerSettingsRoute,
  } as any)
const AuthenticatedOrganizerSettingsNotificationsRoute =
  AuthenticatedOrganizerSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedOrganizerSettingsRoute,
  } as any)
const AuthenticatedOrganizerAthletesAthleteIdRoute =
  AuthenticatedOrganizerAthletesAthleteIdRouteImport.update({
    id: '/$athleteId',
    path: '/$athleteId',
    getParentRoute: () => AuthenticatedOrganizerAthletesRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsIndexRoute =
  AuthenticatedChampionshipsIdTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsNewRoute =
  AuthenticatedChampionshipsIdTeamsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdMatchesMatchIdRoute =
  AuthenticatedChampionshipsIdMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedChampionshipsIdMatchesRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport.update({
    id: '/responsibles',
    path: '/responsibles',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdEditRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdStructureStagesStageIdRoute =
  AuthenticatedChampionshipsIdStructureStagesStageIdRouteImport.update({
    id: '/stages/$stageId',
    path: '/stages/$stageId',
    getParentRoute: () => AuthenticatedChampionshipsIdStructureRoute,
  } as any)
const AuthenticatedChampionshipsIdMatchesMatchIdReportRoute =
  AuthenticatedChampionshipsIdMatchesMatchIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedChampionshipsIdMatchesMatchIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport.update({
    id: '/athletes/new',
    path: '/athletes/new',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport.update({
    id: '/athletes/$athleteId',
    path: '/athletes/$athleteId',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system-admin': typeof SystemAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/system-admin/assinaturas': typeof SystemAdminAssinaturasRoute
  '/system-admin/auditoria': typeof SystemAdminAuditoriaRoute
  '/system-admin/campeonatos': typeof SystemAdminCampeonatosRoute
  '/system-admin/configuracoes': typeof SystemAdminConfiguracoesRoute
  '/system-admin/organizacoes': typeof SystemAdminOrganizacoesRoute
  '/system-admin/suporte': typeof SystemAdminSuporteRoute
  '/system-admin/usuarios': typeof SystemAdminUsuariosRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/team-access/session': typeof TeamAccessSessionRoute
  '/system-admin/': typeof SystemAdminIndexRoute
  '/athletes': typeof AuthenticatedOrganizerAthletesRouteWithChildren
  '/championships': typeof AuthenticatedOrganizerChampionshipsRoute
  '/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/finance': typeof AuthenticatedOrganizerFinanceRoute
  '/matches': typeof AuthenticatedOrganizerMatchesRoute
  '/media': typeof AuthenticatedOrganizerMediaRoute
  '/referees': typeof AuthenticatedOrganizerRefereesRoute
  '/settings': typeof AuthenticatedOrganizerSettingsRouteWithChildren
  '/sponsors': typeof AuthenticatedOrganizerSponsorsRoute
  '/standings': typeof AuthenticatedOrganizerStandingsRoute
  '/stats': typeof AuthenticatedOrganizerStatsRoute
  '/teams': typeof AuthenticatedOrganizerTeamsRouteWithChildren
  '/championships/$id': typeof AuthenticatedChampionshipsIdRouteWithChildren
  '/athletes/$athleteId': typeof AuthenticatedOrganizerAthletesAthleteIdRoute
  '/settings/notifications': typeof AuthenticatedOrganizerSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedOrganizerSettingsOrganizationRoute
  '/settings/public-page': typeof AuthenticatedOrganizerSettingsPublicPageRoute
  '/settings/subscription': typeof AuthenticatedOrganizerSettingsSubscriptionRoute
  '/settings/users': typeof AuthenticatedOrganizerSettingsUsersRoute
  '/teams/$teamId': typeof AuthenticatedOrganizerTeamsTeamIdRoute
  '/championships/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/championships/$id/audit': typeof AuthenticatedChampionshipsIdAuditRoute
  '/championships/$id/configuration': typeof AuthenticatedChampionshipsIdConfigurationRoute
  '/championships/$id/finance': typeof AuthenticatedChampionshipsIdFinanceRoute
  '/championships/$id/matches': typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  '/championships/$id/media': typeof AuthenticatedChampionshipsIdMediaRoute
  '/championships/$id/public-page': typeof AuthenticatedChampionshipsIdPublicPageRoute
  '/championships/$id/referees': typeof AuthenticatedChampionshipsIdRefereesRoute
  '/championships/$id/sanctions': typeof AuthenticatedChampionshipsIdSanctionsRoute
  '/championships/$id/settings': typeof AuthenticatedChampionshipsIdSettingsRoute
  '/championships/$id/sponsors': typeof AuthenticatedChampionshipsIdSponsorsRoute
  '/championships/$id/standings': typeof AuthenticatedChampionshipsIdStandingsRoute
  '/championships/$id/stats': typeof AuthenticatedChampionshipsIdStatsRoute
  '/championships/$id/structure': typeof AuthenticatedChampionshipsIdStructureRouteWithChildren
  '/championships/$id/teams': typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  '/api/billing/infinitepay/webhook': typeof ApiBillingInfinitepayWebhookRoute
  '/athletes/': typeof AuthenticatedOrganizerAthletesIndexRoute
  '/settings/': typeof AuthenticatedOrganizerSettingsIndexRoute
  '/teams/': typeof AuthenticatedOrganizerTeamsIndexRoute
  '/championships/$id/': typeof AuthenticatedChampionshipsIdIndexRoute
  '/championships/$id/matches/$matchId': typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
  '/championships/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  '/championships/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/championships/$id/teams/': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/championships/$id/matches/$matchId/report': typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
  '/championships/$id/structure/stages/$stageId': typeof AuthenticatedChampionshipsIdStructureStagesStageIdRoute
  '/championships/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/championships/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/championships/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/championships/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/championships/$id/teams/$teamId/': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/championships/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/championships/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/system-admin/assinaturas': typeof SystemAdminAssinaturasRoute
  '/system-admin/auditoria': typeof SystemAdminAuditoriaRoute
  '/system-admin/campeonatos': typeof SystemAdminCampeonatosRoute
  '/system-admin/configuracoes': typeof SystemAdminConfiguracoesRoute
  '/system-admin/organizacoes': typeof SystemAdminOrganizacoesRoute
  '/system-admin/suporte': typeof SystemAdminSuporteRoute
  '/system-admin/usuarios': typeof SystemAdminUsuariosRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/team-access/session': typeof TeamAccessSessionRoute
  '/system-admin': typeof SystemAdminIndexRoute
  '/championships': typeof AuthenticatedOrganizerChampionshipsRoute
  '/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/finance': typeof AuthenticatedOrganizerFinanceRoute
  '/matches': typeof AuthenticatedOrganizerMatchesRoute
  '/media': typeof AuthenticatedOrganizerMediaRoute
  '/referees': typeof AuthenticatedOrganizerRefereesRoute
  '/sponsors': typeof AuthenticatedOrganizerSponsorsRoute
  '/standings': typeof AuthenticatedOrganizerStandingsRoute
  '/stats': typeof AuthenticatedOrganizerStatsRoute
  '/athletes/$athleteId': typeof AuthenticatedOrganizerAthletesAthleteIdRoute
  '/settings/notifications': typeof AuthenticatedOrganizerSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedOrganizerSettingsOrganizationRoute
  '/settings/public-page': typeof AuthenticatedOrganizerSettingsPublicPageRoute
  '/settings/subscription': typeof AuthenticatedOrganizerSettingsSubscriptionRoute
  '/settings/users': typeof AuthenticatedOrganizerSettingsUsersRoute
  '/teams/$teamId': typeof AuthenticatedOrganizerTeamsTeamIdRoute
  '/championships/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/championships/$id/audit': typeof AuthenticatedChampionshipsIdAuditRoute
  '/championships/$id/configuration': typeof AuthenticatedChampionshipsIdConfigurationRoute
  '/championships/$id/finance': typeof AuthenticatedChampionshipsIdFinanceRoute
  '/championships/$id/matches': typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  '/championships/$id/media': typeof AuthenticatedChampionshipsIdMediaRoute
  '/championships/$id/public-page': typeof AuthenticatedChampionshipsIdPublicPageRoute
  '/championships/$id/referees': typeof AuthenticatedChampionshipsIdRefereesRoute
  '/championships/$id/sanctions': typeof AuthenticatedChampionshipsIdSanctionsRoute
  '/championships/$id/settings': typeof AuthenticatedChampionshipsIdSettingsRoute
  '/championships/$id/sponsors': typeof AuthenticatedChampionshipsIdSponsorsRoute
  '/championships/$id/standings': typeof AuthenticatedChampionshipsIdStandingsRoute
  '/championships/$id/stats': typeof AuthenticatedChampionshipsIdStatsRoute
  '/championships/$id/structure': typeof AuthenticatedChampionshipsIdStructureRouteWithChildren
  '/api/billing/infinitepay/webhook': typeof ApiBillingInfinitepayWebhookRoute
  '/athletes': typeof AuthenticatedOrganizerAthletesIndexRoute
  '/settings': typeof AuthenticatedOrganizerSettingsIndexRoute
  '/teams': typeof AuthenticatedOrganizerTeamsIndexRoute
  '/championships/$id': typeof AuthenticatedChampionshipsIdIndexRoute
  '/championships/$id/matches/$matchId': typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
  '/championships/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/championships/$id/teams': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/championships/$id/matches/$matchId/report': typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
  '/championships/$id/structure/stages/$stageId': typeof AuthenticatedChampionshipsIdStructureStagesStageIdRoute
  '/championships/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/championships/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/championships/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/championships/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/championships/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/championships/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/championships/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/system-admin': typeof SystemAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_organizer': typeof AuthenticatedOrganizerRouteRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/o/$slug': typeof OSlugRoute
  '/system-admin/assinaturas': typeof SystemAdminAssinaturasRoute
  '/system-admin/auditoria': typeof SystemAdminAuditoriaRoute
  '/system-admin/campeonatos': typeof SystemAdminCampeonatosRoute
  '/system-admin/configuracoes': typeof SystemAdminConfiguracoesRoute
  '/system-admin/organizacoes': typeof SystemAdminOrganizacoesRoute
  '/system-admin/suporte': typeof SystemAdminSuporteRoute
  '/system-admin/usuarios': typeof SystemAdminUsuariosRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/team-access/session': typeof TeamAccessSessionRoute
  '/system-admin/': typeof SystemAdminIndexRoute
  '/_authenticated/_organizer/athletes': typeof AuthenticatedOrganizerAthletesRouteWithChildren
  '/_authenticated/_organizer/championships': typeof AuthenticatedOrganizerChampionshipsRoute
  '/_authenticated/_organizer/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/_authenticated/_organizer/finance': typeof AuthenticatedOrganizerFinanceRoute
  '/_authenticated/_organizer/matches': typeof AuthenticatedOrganizerMatchesRoute
  '/_authenticated/_organizer/media': typeof AuthenticatedOrganizerMediaRoute
  '/_authenticated/_organizer/referees': typeof AuthenticatedOrganizerRefereesRoute
  '/_authenticated/_organizer/settings': typeof AuthenticatedOrganizerSettingsRouteWithChildren
  '/_authenticated/_organizer/sponsors': typeof AuthenticatedOrganizerSponsorsRoute
  '/_authenticated/_organizer/standings': typeof AuthenticatedOrganizerStandingsRoute
  '/_authenticated/_organizer/stats': typeof AuthenticatedOrganizerStatsRoute
  '/_authenticated/_organizer/teams': typeof AuthenticatedOrganizerTeamsRouteWithChildren
  '/_authenticated/championships_/$id': typeof AuthenticatedChampionshipsIdRouteWithChildren
  '/_authenticated/_organizer/athletes/$athleteId': typeof AuthenticatedOrganizerAthletesAthleteIdRoute
  '/_authenticated/_organizer/settings/notifications': typeof AuthenticatedOrganizerSettingsNotificationsRoute
  '/_authenticated/_organizer/settings/organization': typeof AuthenticatedOrganizerSettingsOrganizationRoute
  '/_authenticated/_organizer/settings/public-page': typeof AuthenticatedOrganizerSettingsPublicPageRoute
  '/_authenticated/_organizer/settings/subscription': typeof AuthenticatedOrganizerSettingsSubscriptionRoute
  '/_authenticated/_organizer/settings/users': typeof AuthenticatedOrganizerSettingsUsersRoute
  '/_authenticated/_organizer/teams/$teamId': typeof AuthenticatedOrganizerTeamsTeamIdRoute
  '/_authenticated/championships_/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/_authenticated/championships_/$id/audit': typeof AuthenticatedChampionshipsIdAuditRoute
  '/_authenticated/championships_/$id/configuration': typeof AuthenticatedChampionshipsIdConfigurationRoute
  '/_authenticated/championships_/$id/finance': typeof AuthenticatedChampionshipsIdFinanceRoute
  '/_authenticated/championships_/$id/matches': typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  '/_authenticated/championships_/$id/media': typeof AuthenticatedChampionshipsIdMediaRoute
  '/_authenticated/championships_/$id/public-page': typeof AuthenticatedChampionshipsIdPublicPageRoute
  '/_authenticated/championships_/$id/referees': typeof AuthenticatedChampionshipsIdRefereesRoute
  '/_authenticated/championships_/$id/sanctions': typeof AuthenticatedChampionshipsIdSanctionsRoute
  '/_authenticated/championships_/$id/settings': typeof AuthenticatedChampionshipsIdSettingsRoute
  '/_authenticated/championships_/$id/sponsors': typeof AuthenticatedChampionshipsIdSponsorsRoute
  '/_authenticated/championships_/$id/standings': typeof AuthenticatedChampionshipsIdStandingsRoute
  '/_authenticated/championships_/$id/stats': typeof AuthenticatedChampionshipsIdStatsRoute
  '/_authenticated/championships_/$id/structure': typeof AuthenticatedChampionshipsIdStructureRouteWithChildren
  '/_authenticated/championships_/$id/teams': typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  '/api/billing/infinitepay/webhook': typeof ApiBillingInfinitepayWebhookRoute
  '/_authenticated/_organizer/athletes/': typeof AuthenticatedOrganizerAthletesIndexRoute
  '/_authenticated/_organizer/settings/': typeof AuthenticatedOrganizerSettingsIndexRoute
  '/_authenticated/_organizer/teams/': typeof AuthenticatedOrganizerTeamsIndexRoute
  '/_authenticated/championships_/$id/': typeof AuthenticatedChampionshipsIdIndexRoute
  '/_authenticated/championships_/$id/matches/$matchId': typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
  '/_authenticated/championships_/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  '/_authenticated/championships_/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/_authenticated/championships_/$id/teams/': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/_authenticated/championships_/$id/matches/$matchId/report': typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
  '/_authenticated/championships_/$id/structure/stages/$stageId': typeof AuthenticatedChampionshipsIdStructureStagesStageIdRoute
  '/_authenticated/championships_/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/_authenticated/championships_/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/_authenticated/championships_/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/_authenticated/championships_/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/_authenticated/championships_/$id/teams/$teamId/': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/_authenticated/championships_/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system-admin'
    | '/auth'
    | '/reset-password'
    | '/c/$slug'
    | '/o/$slug'
    | '/system-admin/assinaturas'
    | '/system-admin/auditoria'
    | '/system-admin/campeonatos'
    | '/system-admin/configuracoes'
    | '/system-admin/organizacoes'
    | '/system-admin/suporte'
    | '/system-admin/usuarios'
    | '/team-access/$token'
    | '/team-access/session'
    | '/system-admin/'
    | '/athletes'
    | '/championships'
    | '/dashboard'
    | '/finance'
    | '/matches'
    | '/media'
    | '/referees'
    | '/settings'
    | '/sponsors'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/championships/$id'
    | '/athletes/$athleteId'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/public-page'
    | '/settings/subscription'
    | '/settings/users'
    | '/teams/$teamId'
    | '/championships/$id/athletes'
    | '/championships/$id/audit'
    | '/championships/$id/configuration'
    | '/championships/$id/finance'
    | '/championships/$id/matches'
    | '/championships/$id/media'
    | '/championships/$id/public-page'
    | '/championships/$id/referees'
    | '/championships/$id/sanctions'
    | '/championships/$id/settings'
    | '/championships/$id/sponsors'
    | '/championships/$id/standings'
    | '/championships/$id/stats'
    | '/championships/$id/structure'
    | '/championships/$id/teams'
    | '/api/billing/infinitepay/webhook'
    | '/athletes/'
    | '/settings/'
    | '/teams/'
    | '/championships/$id/'
    | '/championships/$id/matches/$matchId'
    | '/championships/$id/teams/$teamId'
    | '/championships/$id/teams/new'
    | '/championships/$id/teams/'
    | '/championships/$id/matches/$matchId/report'
    | '/championships/$id/structure/stages/$stageId'
    | '/championships/$id/teams/$teamId/edit'
    | '/championships/$id/teams/$teamId/responsibles'
    | '/championships/$id/teams/$teamId/roster'
    | '/championships/$id/teams/$teamId/staff'
    | '/championships/$id/teams/$teamId/'
    | '/championships/$id/teams/$teamId/athletes/$athleteId'
    | '/championships/$id/teams/$teamId/athletes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/c/$slug'
    | '/o/$slug'
    | '/system-admin/assinaturas'
    | '/system-admin/auditoria'
    | '/system-admin/campeonatos'
    | '/system-admin/configuracoes'
    | '/system-admin/organizacoes'
    | '/system-admin/suporte'
    | '/system-admin/usuarios'
    | '/team-access/$token'
    | '/team-access/session'
    | '/system-admin'
    | '/championships'
    | '/dashboard'
    | '/finance'
    | '/matches'
    | '/media'
    | '/referees'
    | '/sponsors'
    | '/standings'
    | '/stats'
    | '/athletes/$athleteId'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/public-page'
    | '/settings/subscription'
    | '/settings/users'
    | '/teams/$teamId'
    | '/championships/$id/athletes'
    | '/championships/$id/audit'
    | '/championships/$id/configuration'
    | '/championships/$id/finance'
    | '/championships/$id/matches'
    | '/championships/$id/media'
    | '/championships/$id/public-page'
    | '/championships/$id/referees'
    | '/championships/$id/sanctions'
    | '/championships/$id/settings'
    | '/championships/$id/sponsors'
    | '/championships/$id/standings'
    | '/championships/$id/stats'
    | '/championships/$id/structure'
    | '/api/billing/infinitepay/webhook'
    | '/athletes'
    | '/settings'
    | '/teams'
    | '/championships/$id'
    | '/championships/$id/matches/$matchId'
    | '/championships/$id/teams/new'
    | '/championships/$id/teams'
    | '/championships/$id/matches/$matchId/report'
    | '/championships/$id/structure/stages/$stageId'
    | '/championships/$id/teams/$teamId/edit'
    | '/championships/$id/teams/$teamId/responsibles'
    | '/championships/$id/teams/$teamId/roster'
    | '/championships/$id/teams/$teamId/staff'
    | '/championships/$id/teams/$teamId'
    | '/championships/$id/teams/$teamId/athletes/$athleteId'
    | '/championships/$id/teams/$teamId/athletes/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/system-admin'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_organizer'
    | '/c/$slug'
    | '/o/$slug'
    | '/system-admin/assinaturas'
    | '/system-admin/auditoria'
    | '/system-admin/campeonatos'
    | '/system-admin/configuracoes'
    | '/system-admin/organizacoes'
    | '/system-admin/suporte'
    | '/system-admin/usuarios'
    | '/team-access/$token'
    | '/team-access/session'
    | '/system-admin/'
    | '/_authenticated/_organizer/athletes'
    | '/_authenticated/_organizer/championships'
    | '/_authenticated/_organizer/dashboard'
    | '/_authenticated/_organizer/finance'
    | '/_authenticated/_organizer/matches'
    | '/_authenticated/_organizer/media'
    | '/_authenticated/_organizer/referees'
    | '/_authenticated/_organizer/settings'
    | '/_authenticated/_organizer/sponsors'
    | '/_authenticated/_organizer/standings'
    | '/_authenticated/_organizer/stats'
    | '/_authenticated/_organizer/teams'
    | '/_authenticated/championships_/$id'
    | '/_authenticated/_organizer/athletes/$athleteId'
    | '/_authenticated/_organizer/settings/notifications'
    | '/_authenticated/_organizer/settings/organization'
    | '/_authenticated/_organizer/settings/public-page'
    | '/_authenticated/_organizer/settings/subscription'
    | '/_authenticated/_organizer/settings/users'
    | '/_authenticated/_organizer/teams/$teamId'
    | '/_authenticated/championships_/$id/athletes'
    | '/_authenticated/championships_/$id/audit'
    | '/_authenticated/championships_/$id/configuration'
    | '/_authenticated/championships_/$id/finance'
    | '/_authenticated/championships_/$id/matches'
    | '/_authenticated/championships_/$id/media'
    | '/_authenticated/championships_/$id/public-page'
    | '/_authenticated/championships_/$id/referees'
    | '/_authenticated/championships_/$id/sanctions'
    | '/_authenticated/championships_/$id/settings'
    | '/_authenticated/championships_/$id/sponsors'
    | '/_authenticated/championships_/$id/standings'
    | '/_authenticated/championships_/$id/stats'
    | '/_authenticated/championships_/$id/structure'
    | '/_authenticated/championships_/$id/teams'
    | '/api/billing/infinitepay/webhook'
    | '/_authenticated/_organizer/athletes/'
    | '/_authenticated/_organizer/settings/'
    | '/_authenticated/_organizer/teams/'
    | '/_authenticated/championships_/$id/'
    | '/_authenticated/championships_/$id/matches/$matchId'
    | '/_authenticated/championships_/$id/teams/$teamId'
    | '/_authenticated/championships_/$id/teams/new'
    | '/_authenticated/championships_/$id/teams/'
    | '/_authenticated/championships_/$id/matches/$matchId/report'
    | '/_authenticated/championships_/$id/structure/stages/$stageId'
    | '/_authenticated/championships_/$id/teams/$teamId/edit'
    | '/_authenticated/championships_/$id/teams/$teamId/responsibles'
    | '/_authenticated/championships_/$id/teams/$teamId/roster'
    | '/_authenticated/championships_/$id/teams/$teamId/staff'
    | '/_authenticated/championships_/$id/teams/$teamId/'
    | '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId'
    | '/_authenticated/championships_/$id/teams/$teamId/athletes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SystemAdminRouteRoute: typeof SystemAdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
  OSlugRoute: typeof OSlugRoute
  TeamAccessTokenRoute: typeof TeamAccessTokenRoute
  TeamAccessSessionRoute: typeof TeamAccessSessionRoute
  ApiBillingInfinitepayWebhookRoute: typeof ApiBillingInfinitepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin': {
      id: '/system-admin'
      path: '/system-admin'
      fullPath: '/system-admin'
      preLoaderRoute: typeof SystemAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin/': {
      id: '/system-admin/'
      path: '/'
      fullPath: '/system-admin/'
      preLoaderRoute: typeof SystemAdminIndexRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/team-access/session': {
      id: '/team-access/session'
      path: '/team-access/session'
      fullPath: '/team-access/session'
      preLoaderRoute: typeof TeamAccessSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-access/$token': {
      id: '/team-access/$token'
      path: '/team-access/$token'
      fullPath: '/team-access/$token'
      preLoaderRoute: typeof TeamAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin/usuarios': {
      id: '/system-admin/usuarios'
      path: '/usuarios'
      fullPath: '/system-admin/usuarios'
      preLoaderRoute: typeof SystemAdminUsuariosRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/system-admin/suporte': {
      id: '/system-admin/suporte'
      path: '/suporte'
      fullPath: '/system-admin/suporte'
      preLoaderRoute: typeof SystemAdminSuporteRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/system-admin/organizacoes': {
      id: '/system-admin/organizacoes'
      path: '/organizacoes'
      fullPath: '/system-admin/organizacoes'
      preLoaderRoute: typeof SystemAdminOrganizacoesRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/system-admin/configuracoes': {
      id: '/system-admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/system-admin/configuracoes'
      preLoaderRoute: typeof SystemAdminConfiguracoesRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/system-admin/campeonatos': {
      id: '/system-admin/campeonatos'
      path: '/campeonatos'
      fullPath: '/system-admin/campeonatos'
      preLoaderRoute: typeof SystemAdminCampeonatosRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/system-admin/auditoria': {
      id: '/system-admin/auditoria'
      path: '/auditoria'
      fullPath: '/system-admin/auditoria'
      preLoaderRoute: typeof SystemAdminAuditoriaRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/system-admin/assinaturas': {
      id: '/system-admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/system-admin/assinaturas'
      preLoaderRoute: typeof SystemAdminAssinaturasRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_organizer': {
      id: '/_authenticated/_organizer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrganizerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/championships_/$id': {
      id: '/_authenticated/championships_/$id'
      path: '/championships/$id'
      fullPath: '/championships/$id'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_organizer/teams': {
      id: '/_authenticated/_organizer/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedOrganizerTeamsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/stats': {
      id: '/_authenticated/_organizer/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedOrganizerStatsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/standings': {
      id: '/_authenticated/_organizer/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedOrganizerStandingsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/sponsors': {
      id: '/_authenticated/_organizer/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AuthenticatedOrganizerSponsorsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/settings': {
      id: '/_authenticated/_organizer/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/referees': {
      id: '/_authenticated/_organizer/referees'
      path: '/referees'
      fullPath: '/referees'
      preLoaderRoute: typeof AuthenticatedOrganizerRefereesRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/media': {
      id: '/_authenticated/_organizer/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedOrganizerMediaRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/matches': {
      id: '/_authenticated/_organizer/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedOrganizerMatchesRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/finance': {
      id: '/_authenticated/_organizer/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedOrganizerFinanceRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/dashboard': {
      id: '/_authenticated/_organizer/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedOrganizerDashboardRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/championships': {
      id: '/_authenticated/_organizer/championships'
      path: '/championships'
      fullPath: '/championships'
      preLoaderRoute: typeof AuthenticatedOrganizerChampionshipsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/athletes': {
      id: '/_authenticated/_organizer/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AuthenticatedOrganizerAthletesRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/championships_/$id/': {
      id: '/_authenticated/championships_/$id/'
      path: '/'
      fullPath: '/championships/$id/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/_organizer/teams/': {
      id: '/_authenticated/_organizer/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedOrganizerTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizerTeamsRoute
    }
    '/_authenticated/_organizer/settings/': {
      id: '/_authenticated/_organizer/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizerSettingsRoute
    }
    '/_authenticated/_organizer/athletes/': {
      id: '/_authenticated/_organizer/athletes/'
      path: '/'
      fullPath: '/athletes/'
      preLoaderRoute: typeof AuthenticatedOrganizerAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizerAthletesRoute
    }
    '/api/billing/infinitepay/webhook': {
      id: '/api/billing/infinitepay/webhook'
      path: '/api/billing/infinitepay/webhook'
      fullPath: '/api/billing/infinitepay/webhook'
      preLoaderRoute: typeof ApiBillingInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/championships_/$id/teams': {
      id: '/_authenticated/championships_/$id/teams'
      path: '/teams'
      fullPath: '/championships/$id/teams'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/structure': {
      id: '/_authenticated/championships_/$id/structure'
      path: '/structure'
      fullPath: '/championships/$id/structure'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdStructureRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/stats': {
      id: '/_authenticated/championships_/$id/stats'
      path: '/stats'
      fullPath: '/championships/$id/stats'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdStatsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/standings': {
      id: '/_authenticated/championships_/$id/standings'
      path: '/standings'
      fullPath: '/championships/$id/standings'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdStandingsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/sponsors': {
      id: '/_authenticated/championships_/$id/sponsors'
      path: '/sponsors'
      fullPath: '/championships/$id/sponsors'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdSponsorsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/settings': {
      id: '/_authenticated/championships_/$id/settings'
      path: '/settings'
      fullPath: '/championships/$id/settings'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/sanctions': {
      id: '/_authenticated/championships_/$id/sanctions'
      path: '/sanctions'
      fullPath: '/championships/$id/sanctions'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdSanctionsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/referees': {
      id: '/_authenticated/championships_/$id/referees'
      path: '/referees'
      fullPath: '/championships/$id/referees'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdRefereesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/public-page': {
      id: '/_authenticated/championships_/$id/public-page'
      path: '/public-page'
      fullPath: '/championships/$id/public-page'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdPublicPageRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/media': {
      id: '/_authenticated/championships_/$id/media'
      path: '/media'
      fullPath: '/championships/$id/media'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMediaRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/matches': {
      id: '/_authenticated/championships_/$id/matches'
      path: '/matches'
      fullPath: '/championships/$id/matches'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMatchesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/finance': {
      id: '/_authenticated/championships_/$id/finance'
      path: '/finance'
      fullPath: '/championships/$id/finance'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdFinanceRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/configuration': {
      id: '/_authenticated/championships_/$id/configuration'
      path: '/configuration'
      fullPath: '/championships/$id/configuration'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdConfigurationRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/audit': {
      id: '/_authenticated/championships_/$id/audit'
      path: '/audit'
      fullPath: '/championships/$id/audit'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdAuditRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/athletes': {
      id: '/_authenticated/championships_/$id/athletes'
      path: '/athletes'
      fullPath: '/championships/$id/athletes'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdAthletesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/_organizer/teams/$teamId': {
      id: '/_authenticated/_organizer/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedOrganizerTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedOrganizerTeamsRoute
    }
    '/_authenticated/_organizer/settings/users': {
      id: '/_authenticated/_organizer/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedOrganizerSettingsRoute
    }
    '/_authenticated/_organizer/settings/subscription': {
      id: '/_authenticated/_organizer/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsSubscriptionRouteImport
      parentRoute: typeof AuthenticatedOrganizerSettingsRoute
    }
    '/_authenticated/_organizer/settings/public-page': {
      id: '/_authenticated/_organizer/settings/public-page'
      path: '/public-page'
      fullPath: '/settings/public-page'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsPublicPageRouteImport
      parentRoute: typeof AuthenticatedOrganizerSettingsRoute
    }
    '/_authenticated/_organizer/settings/organization': {
      id: '/_authenticated/_organizer/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedOrganizerSettingsRoute
    }
    '/_authenticated/_organizer/settings/notifications': {
      id: '/_authenticated/_organizer/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedOrganizerSettingsRoute
    }
    '/_authenticated/_organizer/athletes/$athleteId': {
      id: '/_authenticated/_organizer/athletes/$athleteId'
      path: '/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedOrganizerAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedOrganizerAthletesRoute
    }
    '/_authenticated/championships_/$id/teams/': {
      id: '/_authenticated/championships_/$id/teams/'
      path: '/'
      fullPath: '/championships/$id/teams/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/new': {
      id: '/_authenticated/championships_/$id/teams/new'
      path: '/new'
      fullPath: '/championships/$id/teams/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsNewRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId': {
      id: '/_authenticated/championships_/$id/teams/$teamId'
      path: '/$teamId'
      fullPath: '/championships/$id/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/matches/$matchId': {
      id: '/_authenticated/championships_/$id/matches/$matchId'
      path: '/$matchId'
      fullPath: '/championships/$id/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdMatchesRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/': {
      id: '/_authenticated/championships_/$id/teams/$teamId/'
      path: '/'
      fullPath: '/championships/$id/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/staff': {
      id: '/_authenticated/championships_/$id/teams/$teamId/staff'
      path: '/staff'
      fullPath: '/championships/$id/teams/$teamId/staff'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/roster': {
      id: '/_authenticated/championships_/$id/teams/$teamId/roster'
      path: '/roster'
      fullPath: '/championships/$id/teams/$teamId/roster'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/responsibles': {
      id: '/_authenticated/championships_/$id/teams/$teamId/responsibles'
      path: '/responsibles'
      fullPath: '/championships/$id/teams/$teamId/responsibles'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/edit': {
      id: '/_authenticated/championships_/$id/teams/$teamId/edit'
      path: '/edit'
      fullPath: '/championships/$id/teams/$teamId/edit'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/structure/stages/$stageId': {
      id: '/_authenticated/championships_/$id/structure/stages/$stageId'
      path: '/stages/$stageId'
      fullPath: '/championships/$id/structure/stages/$stageId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdStructureStagesStageIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdStructureRoute
    }
    '/_authenticated/championships_/$id/matches/$matchId/report': {
      id: '/_authenticated/championships_/$id/matches/$matchId/report'
      path: '/report'
      fullPath: '/championships/$id/matches/$matchId/report'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/athletes/new': {
      id: '/_authenticated/championships_/$id/teams/$teamId/athletes/new'
      path: '/athletes/new'
      fullPath: '/championships/$id/teams/$teamId/athletes/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId': {
      id: '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/championships/$id/teams/$teamId/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
  }
}

interface AuthenticatedOrganizerAthletesRouteChildren {
  AuthenticatedOrganizerAthletesAthleteIdRoute: typeof AuthenticatedOrganizerAthletesAthleteIdRoute
  AuthenticatedOrganizerAthletesIndexRoute: typeof AuthenticatedOrganizerAthletesIndexRoute
}

const AuthenticatedOrganizerAthletesRouteChildren: AuthenticatedOrganizerAthletesRouteChildren =
  {
    AuthenticatedOrganizerAthletesAthleteIdRoute:
      AuthenticatedOrganizerAthletesAthleteIdRoute,
    AuthenticatedOrganizerAthletesIndexRoute:
      AuthenticatedOrganizerAthletesIndexRoute,
  }

const AuthenticatedOrganizerAthletesRouteWithChildren =
  AuthenticatedOrganizerAthletesRoute._addFileChildren(
    AuthenticatedOrganizerAthletesRouteChildren,
  )

interface AuthenticatedOrganizerSettingsRouteChildren {
  AuthenticatedOrganizerSettingsNotificationsRoute: typeof AuthenticatedOrganizerSettingsNotificationsRoute
  AuthenticatedOrganizerSettingsOrganizationRoute: typeof AuthenticatedOrganizerSettingsOrganizationRoute
  AuthenticatedOrganizerSettingsPublicPageRoute: typeof AuthenticatedOrganizerSettingsPublicPageRoute
  AuthenticatedOrganizerSettingsSubscriptionRoute: typeof AuthenticatedOrganizerSettingsSubscriptionRoute
  AuthenticatedOrganizerSettingsUsersRoute: typeof AuthenticatedOrganizerSettingsUsersRoute
  AuthenticatedOrganizerSettingsIndexRoute: typeof AuthenticatedOrganizerSettingsIndexRoute
}

const AuthenticatedOrganizerSettingsRouteChildren: AuthenticatedOrganizerSettingsRouteChildren =
  {
    AuthenticatedOrganizerSettingsNotificationsRoute:
      AuthenticatedOrganizerSettingsNotificationsRoute,
    AuthenticatedOrganizerSettingsOrganizationRoute:
      AuthenticatedOrganizerSettingsOrganizationRoute,
    AuthenticatedOrganizerSettingsPublicPageRoute:
      AuthenticatedOrganizerSettingsPublicPageRoute,
    AuthenticatedOrganizerSettingsSubscriptionRoute:
      AuthenticatedOrganizerSettingsSubscriptionRoute,
    AuthenticatedOrganizerSettingsUsersRoute:
      AuthenticatedOrganizerSettingsUsersRoute,
    AuthenticatedOrganizerSettingsIndexRoute:
      AuthenticatedOrganizerSettingsIndexRoute,
  }

const AuthenticatedOrganizerSettingsRouteWithChildren =
  AuthenticatedOrganizerSettingsRoute._addFileChildren(
    AuthenticatedOrganizerSettingsRouteChildren,
  )

interface AuthenticatedOrganizerTeamsRouteChildren {
  AuthenticatedOrganizerTeamsTeamIdRoute: typeof AuthenticatedOrganizerTeamsTeamIdRoute
  AuthenticatedOrganizerTeamsIndexRoute: typeof AuthenticatedOrganizerTeamsIndexRoute
}

const AuthenticatedOrganizerTeamsRouteChildren: AuthenticatedOrganizerTeamsRouteChildren =
  {
    AuthenticatedOrganizerTeamsTeamIdRoute:
      AuthenticatedOrganizerTeamsTeamIdRoute,
    AuthenticatedOrganizerTeamsIndexRoute:
      AuthenticatedOrganizerTeamsIndexRoute,
  }

const AuthenticatedOrganizerTeamsRouteWithChildren =
  AuthenticatedOrganizerTeamsRoute._addFileChildren(
    AuthenticatedOrganizerTeamsRouteChildren,
  )

interface AuthenticatedOrganizerRouteRouteChildren {
  AuthenticatedOrganizerAthletesRoute: typeof AuthenticatedOrganizerAthletesRouteWithChildren
  AuthenticatedOrganizerChampionshipsRoute: typeof AuthenticatedOrganizerChampionshipsRoute
  AuthenticatedOrganizerDashboardRoute: typeof AuthenticatedOrganizerDashboardRoute
  AuthenticatedOrganizerFinanceRoute: typeof AuthenticatedOrganizerFinanceRoute
  AuthenticatedOrganizerMatchesRoute: typeof AuthenticatedOrganizerMatchesRoute
  AuthenticatedOrganizerMediaRoute: typeof AuthenticatedOrganizerMediaRoute
  AuthenticatedOrganizerRefereesRoute: typeof AuthenticatedOrganizerRefereesRoute
  AuthenticatedOrganizerSettingsRoute: typeof AuthenticatedOrganizerSettingsRouteWithChildren
  AuthenticatedOrganizerSponsorsRoute: typeof AuthenticatedOrganizerSponsorsRoute
  AuthenticatedOrganizerStandingsRoute: typeof AuthenticatedOrganizerStandingsRoute
  AuthenticatedOrganizerStatsRoute: typeof AuthenticatedOrganizerStatsRoute
  AuthenticatedOrganizerTeamsRoute: typeof AuthenticatedOrganizerTeamsRouteWithChildren
}

const AuthenticatedOrganizerRouteRouteChildren: AuthenticatedOrganizerRouteRouteChildren =
  {
    AuthenticatedOrganizerAthletesRoute:
      AuthenticatedOrganizerAthletesRouteWithChildren,
    AuthenticatedOrganizerChampionshipsRoute:
      AuthenticatedOrganizerChampionshipsRoute,
    AuthenticatedOrganizerDashboardRoute: AuthenticatedOrganizerDashboardRoute,
    AuthenticatedOrganizerFinanceRoute: AuthenticatedOrganizerFinanceRoute,
    AuthenticatedOrganizerMatchesRoute: AuthenticatedOrganizerMatchesRoute,
    AuthenticatedOrganizerMediaRoute: AuthenticatedOrganizerMediaRoute,
    AuthenticatedOrganizerRefereesRoute: AuthenticatedOrganizerRefereesRoute,
    AuthenticatedOrganizerSettingsRoute:
      AuthenticatedOrganizerSettingsRouteWithChildren,
    AuthenticatedOrganizerSponsorsRoute: AuthenticatedOrganizerSponsorsRoute,
    AuthenticatedOrganizerStandingsRoute: AuthenticatedOrganizerStandingsRoute,
    AuthenticatedOrganizerStatsRoute: AuthenticatedOrganizerStatsRoute,
    AuthenticatedOrganizerTeamsRoute:
      AuthenticatedOrganizerTeamsRouteWithChildren,
  }

const AuthenticatedOrganizerRouteRouteWithChildren =
  AuthenticatedOrganizerRouteRoute._addFileChildren(
    AuthenticatedOrganizerRouteRouteChildren,
  )

interface AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren {
  AuthenticatedChampionshipsIdMatchesMatchIdReportRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
}

const AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren: AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren =
  {
    AuthenticatedChampionshipsIdMatchesMatchIdReportRoute:
      AuthenticatedChampionshipsIdMatchesMatchIdReportRoute,
  }

const AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren =
  AuthenticatedChampionshipsIdMatchesMatchIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren,
  )

interface AuthenticatedChampionshipsIdMatchesRouteChildren {
  AuthenticatedChampionshipsIdMatchesMatchIdRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
}

const AuthenticatedChampionshipsIdMatchesRouteChildren: AuthenticatedChampionshipsIdMatchesRouteChildren =
  {
    AuthenticatedChampionshipsIdMatchesMatchIdRoute:
      AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren,
  }

const AuthenticatedChampionshipsIdMatchesRouteWithChildren =
  AuthenticatedChampionshipsIdMatchesRoute._addFileChildren(
    AuthenticatedChampionshipsIdMatchesRouteChildren,
  )

interface AuthenticatedChampionshipsIdStructureRouteChildren {
  AuthenticatedChampionshipsIdStructureStagesStageIdRoute: typeof AuthenticatedChampionshipsIdStructureStagesStageIdRoute
}

const AuthenticatedChampionshipsIdStructureRouteChildren: AuthenticatedChampionshipsIdStructureRouteChildren =
  {
    AuthenticatedChampionshipsIdStructureStagesStageIdRoute:
      AuthenticatedChampionshipsIdStructureStagesStageIdRoute,
  }

const AuthenticatedChampionshipsIdStructureRouteWithChildren =
  AuthenticatedChampionshipsIdStructureRoute._addFileChildren(
    AuthenticatedChampionshipsIdStructureRouteChildren,
  )

interface AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren {
  AuthenticatedChampionshipsIdTeamsTeamIdEditRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}

const AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren: AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren =
  {
    AuthenticatedChampionshipsIdTeamsTeamIdEditRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdEditRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute,
  }

const AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren =
  AuthenticatedChampionshipsIdTeamsTeamIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren,
  )

interface AuthenticatedChampionshipsIdTeamsRouteChildren {
  AuthenticatedChampionshipsIdTeamsTeamIdRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  AuthenticatedChampionshipsIdTeamsNewRoute: typeof AuthenticatedChampionshipsIdTeamsNewRoute
  AuthenticatedChampionshipsIdTeamsIndexRoute: typeof AuthenticatedChampionshipsIdTeamsIndexRoute
}

const AuthenticatedChampionshipsIdTeamsRouteChildren: AuthenticatedChampionshipsIdTeamsRouteChildren =
  {
    AuthenticatedChampionshipsIdTeamsTeamIdRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren,
    AuthenticatedChampionshipsIdTeamsNewRoute:
      AuthenticatedChampionshipsIdTeamsNewRoute,
    AuthenticatedChampionshipsIdTeamsIndexRoute:
      AuthenticatedChampionshipsIdTeamsIndexRoute,
  }

const AuthenticatedChampionshipsIdTeamsRouteWithChildren =
  AuthenticatedChampionshipsIdTeamsRoute._addFileChildren(
    AuthenticatedChampionshipsIdTeamsRouteChildren,
  )

interface AuthenticatedChampionshipsIdRouteChildren {
  AuthenticatedChampionshipsIdAthletesRoute: typeof AuthenticatedChampionshipsIdAthletesRoute
  AuthenticatedChampionshipsIdAuditRoute: typeof AuthenticatedChampionshipsIdAuditRoute
  AuthenticatedChampionshipsIdConfigurationRoute: typeof AuthenticatedChampionshipsIdConfigurationRoute
  AuthenticatedChampionshipsIdFinanceRoute: typeof AuthenticatedChampionshipsIdFinanceRoute
  AuthenticatedChampionshipsIdMatchesRoute: typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  AuthenticatedChampionshipsIdMediaRoute: typeof AuthenticatedChampionshipsIdMediaRoute
  AuthenticatedChampionshipsIdPublicPageRoute: typeof AuthenticatedChampionshipsIdPublicPageRoute
  AuthenticatedChampionshipsIdRefereesRoute: typeof AuthenticatedChampionshipsIdRefereesRoute
  AuthenticatedChampionshipsIdSanctionsRoute: typeof AuthenticatedChampionshipsIdSanctionsRoute
  AuthenticatedChampionshipsIdSettingsRoute: typeof AuthenticatedChampionshipsIdSettingsRoute
  AuthenticatedChampionshipsIdSponsorsRoute: typeof AuthenticatedChampionshipsIdSponsorsRoute
  AuthenticatedChampionshipsIdStandingsRoute: typeof AuthenticatedChampionshipsIdStandingsRoute
  AuthenticatedChampionshipsIdStatsRoute: typeof AuthenticatedChampionshipsIdStatsRoute
  AuthenticatedChampionshipsIdStructureRoute: typeof AuthenticatedChampionshipsIdStructureRouteWithChildren
  AuthenticatedChampionshipsIdTeamsRoute: typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  AuthenticatedChampionshipsIdIndexRoute: typeof AuthenticatedChampionshipsIdIndexRoute
}

const AuthenticatedChampionshipsIdRouteChildren: AuthenticatedChampionshipsIdRouteChildren =
  {
    AuthenticatedChampionshipsIdAthletesRoute:
      AuthenticatedChampionshipsIdAthletesRoute,
    AuthenticatedChampionshipsIdAuditRoute:
      AuthenticatedChampionshipsIdAuditRoute,
    AuthenticatedChampionshipsIdConfigurationRoute:
      AuthenticatedChampionshipsIdConfigurationRoute,
    AuthenticatedChampionshipsIdFinanceRoute:
      AuthenticatedChampionshipsIdFinanceRoute,
    AuthenticatedChampionshipsIdMatchesRoute:
      AuthenticatedChampionshipsIdMatchesRouteWithChildren,
    AuthenticatedChampionshipsIdMediaRoute:
      AuthenticatedChampionshipsIdMediaRoute,
    AuthenticatedChampionshipsIdPublicPageRoute:
      AuthenticatedChampionshipsIdPublicPageRoute,
    AuthenticatedChampionshipsIdRefereesRoute:
      AuthenticatedChampionshipsIdRefereesRoute,
    AuthenticatedChampionshipsIdSanctionsRoute:
      AuthenticatedChampionshipsIdSanctionsRoute,
    AuthenticatedChampionshipsIdSettingsRoute:
      AuthenticatedChampionshipsIdSettingsRoute,
    AuthenticatedChampionshipsIdSponsorsRoute:
      AuthenticatedChampionshipsIdSponsorsRoute,
    AuthenticatedChampionshipsIdStandingsRoute:
      AuthenticatedChampionshipsIdStandingsRoute,
    AuthenticatedChampionshipsIdStatsRoute:
      AuthenticatedChampionshipsIdStatsRoute,
    AuthenticatedChampionshipsIdStructureRoute:
      AuthenticatedChampionshipsIdStructureRouteWithChildren,
    AuthenticatedChampionshipsIdTeamsRoute:
      AuthenticatedChampionshipsIdTeamsRouteWithChildren,
    AuthenticatedChampionshipsIdIndexRoute:
      AuthenticatedChampionshipsIdIndexRoute,
  }

const AuthenticatedChampionshipsIdRouteWithChildren =
  AuthenticatedChampionshipsIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrganizerRouteRoute: typeof AuthenticatedOrganizerRouteRouteWithChildren
  AuthenticatedChampionshipsIdRoute: typeof AuthenticatedChampionshipsIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrganizerRouteRoute:
    AuthenticatedOrganizerRouteRouteWithChildren,
  AuthenticatedChampionshipsIdRoute:
    AuthenticatedChampionshipsIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SystemAdminRouteRouteChildren {
  SystemAdminAssinaturasRoute: typeof SystemAdminAssinaturasRoute
  SystemAdminAuditoriaRoute: typeof SystemAdminAuditoriaRoute
  SystemAdminCampeonatosRoute: typeof SystemAdminCampeonatosRoute
  SystemAdminConfiguracoesRoute: typeof SystemAdminConfiguracoesRoute
  SystemAdminOrganizacoesRoute: typeof SystemAdminOrganizacoesRoute
  SystemAdminSuporteRoute: typeof SystemAdminSuporteRoute
  SystemAdminUsuariosRoute: typeof SystemAdminUsuariosRoute
  SystemAdminIndexRoute: typeof SystemAdminIndexRoute
}

const SystemAdminRouteRouteChildren: SystemAdminRouteRouteChildren = {
  SystemAdminAssinaturasRoute: SystemAdminAssinaturasRoute,
  SystemAdminAuditoriaRoute: SystemAdminAuditoriaRoute,
  SystemAdminCampeonatosRoute: SystemAdminCampeonatosRoute,
  SystemAdminConfiguracoesRoute: SystemAdminConfiguracoesRoute,
  SystemAdminOrganizacoesRoute: SystemAdminOrganizacoesRoute,
  SystemAdminSuporteRoute: SystemAdminSuporteRoute,
  SystemAdminUsuariosRoute: SystemAdminUsuariosRoute,
  SystemAdminIndexRoute: SystemAdminIndexRoute,
}

const SystemAdminRouteRouteWithChildren =
  SystemAdminRouteRoute._addFileChildren(SystemAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SystemAdminRouteRoute: SystemAdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CSlugRoute: CSlugRoute,
  OSlugRoute: OSlugRoute,
  TeamAccessTokenRoute: TeamAccessTokenRoute,
  TeamAccessSessionRoute: TeamAccessSessionRoute,
  ApiBillingInfinitepayWebhookRoute: ApiBillingInfinitepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
