/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SystemAdminRouteRouteImport } from './routes/system-admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemAdminIndexRouteImport } from './routes/system-admin/index'
import { Route as TeamAccessSessionRouteImport } from './routes/team-access.session'
import { Route as TeamAccessTokenRouteImport } from './routes/team-access.$token'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedOrganizerRouteRouteImport } from './routes/_authenticated/_organizer/route'
import { Route as AuthenticatedChampionshipsIdRouteImport } from './routes/_authenticated/championships_.$id'
import { Route as AuthenticatedOrganizerTeamsRouteImport } from './routes/_authenticated/_organizer/teams'
import { Route as AuthenticatedOrganizerStatsRouteImport } from './routes/_authenticated/_organizer/stats'
import { Route as AuthenticatedOrganizerStandingsRouteImport } from './routes/_authenticated/_organizer/standings'
import { Route as AuthenticatedOrganizerSponsorsRouteImport } from './routes/_authenticated/_organizer/sponsors'
import { Route as AuthenticatedOrganizerSettingsRouteImport } from './routes/_authenticated/_organizer/settings'
import { Route as AuthenticatedOrganizerRefereesRouteImport } from './routes/_authenticated/_organizer/referees'
import { Route as AuthenticatedOrganizerMediaRouteImport } from './routes/_authenticated/_organizer/media'
import { Route as AuthenticatedOrganizerMatchesRouteImport } from './routes/_authenticated/_organizer/matches'
import { Route as AuthenticatedOrganizerFinanceRouteImport } from './routes/_authenticated/_organizer/finance'
import { Route as AuthenticatedOrganizerDashboardRouteImport } from './routes/_authenticated/_organizer/dashboard'
import { Route as AuthenticatedOrganizerChampionshipsRouteImport } from './routes/_authenticated/_organizer/championships'
import { Route as AuthenticatedOrganizerAthletesRouteImport } from './routes/_authenticated/_organizer/athletes'
import { Route as AuthenticatedChampionshipsIdIndexRouteImport } from './routes/_authenticated/championships_.$id.index'
import { Route as AuthenticatedChampionshipsIdTeamsRouteImport } from './routes/_authenticated/championships_.$id.teams'
import { Route as AuthenticatedChampionshipsIdStatsRouteImport } from './routes/_authenticated/championships_.$id.stats'
import { Route as AuthenticatedChampionshipsIdStandingsRouteImport } from './routes/_authenticated/championships_.$id.standings'
import { Route as AuthenticatedChampionshipsIdMatchesRouteImport } from './routes/_authenticated/championships_.$id.matches'
import { Route as AuthenticatedChampionshipsIdAthletesRouteImport } from './routes/_authenticated/championships_.$id.athletes'
import { Route as AuthenticatedChampionshipsIdTeamsIndexRouteImport } from './routes/_authenticated/championships_.$id.teams.index'
import { Route as AuthenticatedChampionshipsIdTeamsNewRouteImport } from './routes/_authenticated/championships_.$id.teams.new'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId'
import { Route as AuthenticatedChampionshipsIdMatchesMatchIdRouteImport } from './routes/_authenticated/championships_.$id.matches.$matchId'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.index'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.staff'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.roster'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.responsibles'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.edit'
import { Route as AuthenticatedChampionshipsIdMatchesMatchIdReportRouteImport } from './routes/_authenticated/championships_.$id.matches.$matchId.report'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.athletes.new'
import { Route as AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport } from './routes/_authenticated/championships_.$id.teams.$teamId.athletes.$athleteId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminRouteRoute = SystemAdminRouteRouteImport.update({
  id: '/system-admin',
  path: '/system-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminIndexRoute = SystemAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemAdminRouteRoute,
} as any)
const TeamAccessSessionRoute = TeamAccessSessionRouteImport.update({
  id: '/team-access/session',
  path: '/team-access/session',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAccessTokenRoute = TeamAccessTokenRouteImport.update({
  id: '/team-access/$token',
  path: '/team-access/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizerRouteRoute =
  AuthenticatedOrganizerRouteRouteImport.update({
    id: '/_organizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChampionshipsIdRoute =
  AuthenticatedChampionshipsIdRouteImport.update({
    id: '/championships_/$id',
    path: '/championships/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerTeamsRoute =
  AuthenticatedOrganizerTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerStatsRoute =
  AuthenticatedOrganizerStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerStandingsRoute =
  AuthenticatedOrganizerStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerSponsorsRoute =
  AuthenticatedOrganizerSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerSettingsRoute =
  AuthenticatedOrganizerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerRefereesRoute =
  AuthenticatedOrganizerRefereesRouteImport.update({
    id: '/referees',
    path: '/referees',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerMediaRoute =
  AuthenticatedOrganizerMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerMatchesRoute =
  AuthenticatedOrganizerMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerFinanceRoute =
  AuthenticatedOrganizerFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerDashboardRoute =
  AuthenticatedOrganizerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerChampionshipsRoute =
  AuthenticatedOrganizerChampionshipsRouteImport.update({
    id: '/championships',
    path: '/championships',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedOrganizerAthletesRoute =
  AuthenticatedOrganizerAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedOrganizerRouteRoute,
  } as any)
const AuthenticatedChampionshipsIdIndexRoute =
  AuthenticatedChampionshipsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsRoute =
  AuthenticatedChampionshipsIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdStatsRoute =
  AuthenticatedChampionshipsIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdStandingsRoute =
  AuthenticatedChampionshipsIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdMatchesRoute =
  AuthenticatedChampionshipsIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdAthletesRoute =
  AuthenticatedChampionshipsIdAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedChampionshipsIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsIndexRoute =
  AuthenticatedChampionshipsIdTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsNewRoute =
  AuthenticatedChampionshipsIdTeamsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsRoute,
  } as any)
const AuthenticatedChampionshipsIdMatchesMatchIdRoute =
  AuthenticatedChampionshipsIdMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedChampionshipsIdMatchesRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport.update({
    id: '/responsibles',
    path: '/responsibles',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdEditRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdMatchesMatchIdReportRoute =
  AuthenticatedChampionshipsIdMatchesMatchIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedChampionshipsIdMatchesMatchIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport.update({
    id: '/athletes/new',
    path: '/athletes/new',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute =
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport.update({
    id: '/athletes/$athleteId',
    path: '/athletes/$athleteId',
    getParentRoute: () => AuthenticatedChampionshipsIdTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system-admin': typeof SystemAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/team-access/session': typeof TeamAccessSessionRoute
  '/system-admin/': typeof SystemAdminIndexRoute
  '/athletes': typeof AuthenticatedOrganizerAthletesRoute
  '/championships': typeof AuthenticatedOrganizerChampionshipsRoute
  '/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/finance': typeof AuthenticatedOrganizerFinanceRoute
  '/matches': typeof AuthenticatedOrganizerMatchesRoute
  '/media': typeof AuthenticatedOrganizerMediaRoute
  '/referees': typeof AuthenticatedOrganizerRefereesRoute
  '/settings': typeof AuthenticatedOrganizerSettingsRoute
  '/sponsors': typeof AuthenticatedOrganizerSponsorsRoute
  '/standings': typeof AuthenticatedOrganizerStandingsRoute
  '/stats': typeof AuthenticatedOrganizerStatsRoute
  '/teams': typeof AuthenticatedOrganizerTeamsRoute
  '/championships/$id': typeof AuthenticatedChampionshipsIdRouteWithChildren
  '/championships/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/championships/$id/matches': typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  '/championships/$id/standings': typeof AuthenticatedChampionshipsIdStandingsRoute
  '/championships/$id/stats': typeof AuthenticatedChampionshipsIdStatsRoute
  '/championships/$id/teams': typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  '/championships/$id/': typeof AuthenticatedChampionshipsIdIndexRoute
  '/championships/$id/matches/$matchId': typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
  '/championships/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  '/championships/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/championships/$id/teams/': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/championships/$id/matches/$matchId/report': typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
  '/championships/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/championships/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/championships/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/championships/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/championships/$id/teams/$teamId/': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/championships/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/championships/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/team-access/session': typeof TeamAccessSessionRoute
  '/system-admin': typeof SystemAdminIndexRoute
  '/athletes': typeof AuthenticatedOrganizerAthletesRoute
  '/championships': typeof AuthenticatedOrganizerChampionshipsRoute
  '/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/finance': typeof AuthenticatedOrganizerFinanceRoute
  '/matches': typeof AuthenticatedOrganizerMatchesRoute
  '/media': typeof AuthenticatedOrganizerMediaRoute
  '/referees': typeof AuthenticatedOrganizerRefereesRoute
  '/settings': typeof AuthenticatedOrganizerSettingsRoute
  '/sponsors': typeof AuthenticatedOrganizerSponsorsRoute
  '/standings': typeof AuthenticatedOrganizerStandingsRoute
  '/stats': typeof AuthenticatedOrganizerStatsRoute
  '/teams': typeof AuthenticatedOrganizerTeamsRoute
  '/championships/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/championships/$id/matches': typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  '/championships/$id/standings': typeof AuthenticatedChampionshipsIdStandingsRoute
  '/championships/$id/stats': typeof AuthenticatedChampionshipsIdStatsRoute
  '/championships/$id': typeof AuthenticatedChampionshipsIdIndexRoute
  '/championships/$id/matches/$matchId': typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
  '/championships/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/championships/$id/teams': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/championships/$id/matches/$matchId/report': typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
  '/championships/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/championships/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/championships/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/championships/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/championships/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/championships/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/championships/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/system-admin': typeof SystemAdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_organizer': typeof AuthenticatedOrganizerRouteRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/team-access/session': typeof TeamAccessSessionRoute
  '/system-admin/': typeof SystemAdminIndexRoute
  '/_authenticated/_organizer/athletes': typeof AuthenticatedOrganizerAthletesRoute
  '/_authenticated/_organizer/championships': typeof AuthenticatedOrganizerChampionshipsRoute
  '/_authenticated/_organizer/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/_authenticated/_organizer/finance': typeof AuthenticatedOrganizerFinanceRoute
  '/_authenticated/_organizer/matches': typeof AuthenticatedOrganizerMatchesRoute
  '/_authenticated/_organizer/media': typeof AuthenticatedOrganizerMediaRoute
  '/_authenticated/_organizer/referees': typeof AuthenticatedOrganizerRefereesRoute
  '/_authenticated/_organizer/settings': typeof AuthenticatedOrganizerSettingsRoute
  '/_authenticated/_organizer/sponsors': typeof AuthenticatedOrganizerSponsorsRoute
  '/_authenticated/_organizer/standings': typeof AuthenticatedOrganizerStandingsRoute
  '/_authenticated/_organizer/stats': typeof AuthenticatedOrganizerStatsRoute
  '/_authenticated/_organizer/teams': typeof AuthenticatedOrganizerTeamsRoute
  '/_authenticated/championships_/$id': typeof AuthenticatedChampionshipsIdRouteWithChildren
  '/_authenticated/championships_/$id/athletes': typeof AuthenticatedChampionshipsIdAthletesRoute
  '/_authenticated/championships_/$id/matches': typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  '/_authenticated/championships_/$id/standings': typeof AuthenticatedChampionshipsIdStandingsRoute
  '/_authenticated/championships_/$id/stats': typeof AuthenticatedChampionshipsIdStatsRoute
  '/_authenticated/championships_/$id/teams': typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  '/_authenticated/championships_/$id/': typeof AuthenticatedChampionshipsIdIndexRoute
  '/_authenticated/championships_/$id/matches/$matchId': typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
  '/_authenticated/championships_/$id/teams/$teamId': typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  '/_authenticated/championships_/$id/teams/new': typeof AuthenticatedChampionshipsIdTeamsNewRoute
  '/_authenticated/championships_/$id/teams/': typeof AuthenticatedChampionshipsIdTeamsIndexRoute
  '/_authenticated/championships_/$id/matches/$matchId/report': typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
  '/_authenticated/championships_/$id/teams/$teamId/edit': typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  '/_authenticated/championships_/$id/teams/$teamId/responsibles': typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  '/_authenticated/championships_/$id/teams/$teamId/roster': typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  '/_authenticated/championships_/$id/teams/$teamId/staff': typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  '/_authenticated/championships_/$id/teams/$teamId/': typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  '/_authenticated/championships_/$id/teams/$teamId/athletes/new': typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system-admin'
    | '/auth'
    | '/reset-password'
    | '/c/$slug'
    | '/team-access/$token'
    | '/team-access/session'
    | '/system-admin/'
    | '/athletes'
    | '/championships'
    | '/dashboard'
    | '/finance'
    | '/matches'
    | '/media'
    | '/referees'
    | '/settings'
    | '/sponsors'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/championships/$id'
    | '/championships/$id/athletes'
    | '/championships/$id/matches'
    | '/championships/$id/standings'
    | '/championships/$id/stats'
    | '/championships/$id/teams'
    | '/championships/$id/'
    | '/championships/$id/matches/$matchId'
    | '/championships/$id/teams/$teamId'
    | '/championships/$id/teams/new'
    | '/championships/$id/teams/'
    | '/championships/$id/matches/$matchId/report'
    | '/championships/$id/teams/$teamId/edit'
    | '/championships/$id/teams/$teamId/responsibles'
    | '/championships/$id/teams/$teamId/roster'
    | '/championships/$id/teams/$teamId/staff'
    | '/championships/$id/teams/$teamId/'
    | '/championships/$id/teams/$teamId/athletes/$athleteId'
    | '/championships/$id/teams/$teamId/athletes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/c/$slug'
    | '/team-access/$token'
    | '/team-access/session'
    | '/system-admin'
    | '/athletes'
    | '/championships'
    | '/dashboard'
    | '/finance'
    | '/matches'
    | '/media'
    | '/referees'
    | '/settings'
    | '/sponsors'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/championships/$id/athletes'
    | '/championships/$id/matches'
    | '/championships/$id/standings'
    | '/championships/$id/stats'
    | '/championships/$id'
    | '/championships/$id/matches/$matchId'
    | '/championships/$id/teams/new'
    | '/championships/$id/teams'
    | '/championships/$id/matches/$matchId/report'
    | '/championships/$id/teams/$teamId/edit'
    | '/championships/$id/teams/$teamId/responsibles'
    | '/championships/$id/teams/$teamId/roster'
    | '/championships/$id/teams/$teamId/staff'
    | '/championships/$id/teams/$teamId'
    | '/championships/$id/teams/$teamId/athletes/$athleteId'
    | '/championships/$id/teams/$teamId/athletes/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/system-admin'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_organizer'
    | '/c/$slug'
    | '/team-access/$token'
    | '/team-access/session'
    | '/system-admin/'
    | '/_authenticated/_organizer/athletes'
    | '/_authenticated/_organizer/championships'
    | '/_authenticated/_organizer/dashboard'
    | '/_authenticated/_organizer/finance'
    | '/_authenticated/_organizer/matches'
    | '/_authenticated/_organizer/media'
    | '/_authenticated/_organizer/referees'
    | '/_authenticated/_organizer/settings'
    | '/_authenticated/_organizer/sponsors'
    | '/_authenticated/_organizer/standings'
    | '/_authenticated/_organizer/stats'
    | '/_authenticated/_organizer/teams'
    | '/_authenticated/championships_/$id'
    | '/_authenticated/championships_/$id/athletes'
    | '/_authenticated/championships_/$id/matches'
    | '/_authenticated/championships_/$id/standings'
    | '/_authenticated/championships_/$id/stats'
    | '/_authenticated/championships_/$id/teams'
    | '/_authenticated/championships_/$id/'
    | '/_authenticated/championships_/$id/matches/$matchId'
    | '/_authenticated/championships_/$id/teams/$teamId'
    | '/_authenticated/championships_/$id/teams/new'
    | '/_authenticated/championships_/$id/teams/'
    | '/_authenticated/championships_/$id/matches/$matchId/report'
    | '/_authenticated/championships_/$id/teams/$teamId/edit'
    | '/_authenticated/championships_/$id/teams/$teamId/responsibles'
    | '/_authenticated/championships_/$id/teams/$teamId/roster'
    | '/_authenticated/championships_/$id/teams/$teamId/staff'
    | '/_authenticated/championships_/$id/teams/$teamId/'
    | '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId'
    | '/_authenticated/championships_/$id/teams/$teamId/athletes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SystemAdminRouteRoute: typeof SystemAdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
  TeamAccessTokenRoute: typeof TeamAccessTokenRoute
  TeamAccessSessionRoute: typeof TeamAccessSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin': {
      id: '/system-admin'
      path: '/system-admin'
      fullPath: '/system-admin'
      preLoaderRoute: typeof SystemAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin/': {
      id: '/system-admin/'
      path: '/'
      fullPath: '/system-admin/'
      preLoaderRoute: typeof SystemAdminIndexRouteImport
      parentRoute: typeof SystemAdminRouteRoute
    }
    '/team-access/session': {
      id: '/team-access/session'
      path: '/team-access/session'
      fullPath: '/team-access/session'
      preLoaderRoute: typeof TeamAccessSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-access/$token': {
      id: '/team-access/$token'
      path: '/team-access/$token'
      fullPath: '/team-access/$token'
      preLoaderRoute: typeof TeamAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_organizer': {
      id: '/_authenticated/_organizer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrganizerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/championships_/$id': {
      id: '/_authenticated/championships_/$id'
      path: '/championships/$id'
      fullPath: '/championships/$id'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_organizer/teams': {
      id: '/_authenticated/_organizer/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedOrganizerTeamsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/stats': {
      id: '/_authenticated/_organizer/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedOrganizerStatsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/standings': {
      id: '/_authenticated/_organizer/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof AuthenticatedOrganizerStandingsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/sponsors': {
      id: '/_authenticated/_organizer/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AuthenticatedOrganizerSponsorsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/settings': {
      id: '/_authenticated/_organizer/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedOrganizerSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/referees': {
      id: '/_authenticated/_organizer/referees'
      path: '/referees'
      fullPath: '/referees'
      preLoaderRoute: typeof AuthenticatedOrganizerRefereesRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/media': {
      id: '/_authenticated/_organizer/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedOrganizerMediaRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/matches': {
      id: '/_authenticated/_organizer/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedOrganizerMatchesRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/finance': {
      id: '/_authenticated/_organizer/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedOrganizerFinanceRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/dashboard': {
      id: '/_authenticated/_organizer/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedOrganizerDashboardRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/championships': {
      id: '/_authenticated/_organizer/championships'
      path: '/championships'
      fullPath: '/championships'
      preLoaderRoute: typeof AuthenticatedOrganizerChampionshipsRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/_organizer/athletes': {
      id: '/_authenticated/_organizer/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AuthenticatedOrganizerAthletesRouteImport
      parentRoute: typeof AuthenticatedOrganizerRouteRoute
    }
    '/_authenticated/championships_/$id/': {
      id: '/_authenticated/championships_/$id/'
      path: '/'
      fullPath: '/championships/$id/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/teams': {
      id: '/_authenticated/championships_/$id/teams'
      path: '/teams'
      fullPath: '/championships/$id/teams'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/stats': {
      id: '/_authenticated/championships_/$id/stats'
      path: '/stats'
      fullPath: '/championships/$id/stats'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdStatsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/standings': {
      id: '/_authenticated/championships_/$id/standings'
      path: '/standings'
      fullPath: '/championships/$id/standings'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdStandingsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/matches': {
      id: '/_authenticated/championships_/$id/matches'
      path: '/matches'
      fullPath: '/championships/$id/matches'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMatchesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/athletes': {
      id: '/_authenticated/championships_/$id/athletes'
      path: '/athletes'
      fullPath: '/championships/$id/athletes'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdAthletesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdRoute
    }
    '/_authenticated/championships_/$id/teams/': {
      id: '/_authenticated/championships_/$id/teams/'
      path: '/'
      fullPath: '/championships/$id/teams/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/new': {
      id: '/_authenticated/championships_/$id/teams/new'
      path: '/new'
      fullPath: '/championships/$id/teams/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsNewRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId': {
      id: '/_authenticated/championships_/$id/teams/$teamId'
      path: '/$teamId'
      fullPath: '/championships/$id/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsRoute
    }
    '/_authenticated/championships_/$id/matches/$matchId': {
      id: '/_authenticated/championships_/$id/matches/$matchId'
      path: '/$matchId'
      fullPath: '/championships/$id/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdMatchesRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/': {
      id: '/_authenticated/championships_/$id/teams/$teamId/'
      path: '/'
      fullPath: '/championships/$id/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/staff': {
      id: '/_authenticated/championships_/$id/teams/$teamId/staff'
      path: '/staff'
      fullPath: '/championships/$id/teams/$teamId/staff'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/roster': {
      id: '/_authenticated/championships_/$id/teams/$teamId/roster'
      path: '/roster'
      fullPath: '/championships/$id/teams/$teamId/roster'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/responsibles': {
      id: '/_authenticated/championships_/$id/teams/$teamId/responsibles'
      path: '/responsibles'
      fullPath: '/championships/$id/teams/$teamId/responsibles'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/edit': {
      id: '/_authenticated/championships_/$id/teams/$teamId/edit'
      path: '/edit'
      fullPath: '/championships/$id/teams/$teamId/edit'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/matches/$matchId/report': {
      id: '/_authenticated/championships_/$id/matches/$matchId/report'
      path: '/report'
      fullPath: '/championships/$id/matches/$matchId/report'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/athletes/new': {
      id: '/_authenticated/championships_/$id/teams/$teamId/athletes/new'
      path: '/athletes/new'
      fullPath: '/championships/$id/teams/$teamId/athletes/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
    '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId': {
      id: '/_authenticated/championships_/$id/teams/$teamId/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/championships/$id/teams/$teamId/athletes/$athleteId'
      preLoaderRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRoute
    }
  }
}

interface AuthenticatedOrganizerRouteRouteChildren {
  AuthenticatedOrganizerAthletesRoute: typeof AuthenticatedOrganizerAthletesRoute
  AuthenticatedOrganizerChampionshipsRoute: typeof AuthenticatedOrganizerChampionshipsRoute
  AuthenticatedOrganizerDashboardRoute: typeof AuthenticatedOrganizerDashboardRoute
  AuthenticatedOrganizerFinanceRoute: typeof AuthenticatedOrganizerFinanceRoute
  AuthenticatedOrganizerMatchesRoute: typeof AuthenticatedOrganizerMatchesRoute
  AuthenticatedOrganizerMediaRoute: typeof AuthenticatedOrganizerMediaRoute
  AuthenticatedOrganizerRefereesRoute: typeof AuthenticatedOrganizerRefereesRoute
  AuthenticatedOrganizerSettingsRoute: typeof AuthenticatedOrganizerSettingsRoute
  AuthenticatedOrganizerSponsorsRoute: typeof AuthenticatedOrganizerSponsorsRoute
  AuthenticatedOrganizerStandingsRoute: typeof AuthenticatedOrganizerStandingsRoute
  AuthenticatedOrganizerStatsRoute: typeof AuthenticatedOrganizerStatsRoute
  AuthenticatedOrganizerTeamsRoute: typeof AuthenticatedOrganizerTeamsRoute
}

const AuthenticatedOrganizerRouteRouteChildren: AuthenticatedOrganizerRouteRouteChildren =
  {
    AuthenticatedOrganizerAthletesRoute: AuthenticatedOrganizerAthletesRoute,
    AuthenticatedOrganizerChampionshipsRoute:
      AuthenticatedOrganizerChampionshipsRoute,
    AuthenticatedOrganizerDashboardRoute: AuthenticatedOrganizerDashboardRoute,
    AuthenticatedOrganizerFinanceRoute: AuthenticatedOrganizerFinanceRoute,
    AuthenticatedOrganizerMatchesRoute: AuthenticatedOrganizerMatchesRoute,
    AuthenticatedOrganizerMediaRoute: AuthenticatedOrganizerMediaRoute,
    AuthenticatedOrganizerRefereesRoute: AuthenticatedOrganizerRefereesRoute,
    AuthenticatedOrganizerSettingsRoute: AuthenticatedOrganizerSettingsRoute,
    AuthenticatedOrganizerSponsorsRoute: AuthenticatedOrganizerSponsorsRoute,
    AuthenticatedOrganizerStandingsRoute: AuthenticatedOrganizerStandingsRoute,
    AuthenticatedOrganizerStatsRoute: AuthenticatedOrganizerStatsRoute,
    AuthenticatedOrganizerTeamsRoute: AuthenticatedOrganizerTeamsRoute,
  }

const AuthenticatedOrganizerRouteRouteWithChildren =
  AuthenticatedOrganizerRouteRoute._addFileChildren(
    AuthenticatedOrganizerRouteRouteChildren,
  )

interface AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren {
  AuthenticatedChampionshipsIdMatchesMatchIdReportRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdReportRoute
}

const AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren: AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren =
  {
    AuthenticatedChampionshipsIdMatchesMatchIdReportRoute:
      AuthenticatedChampionshipsIdMatchesMatchIdReportRoute,
  }

const AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren =
  AuthenticatedChampionshipsIdMatchesMatchIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdMatchesMatchIdRouteChildren,
  )

interface AuthenticatedChampionshipsIdMatchesRouteChildren {
  AuthenticatedChampionshipsIdMatchesMatchIdRoute: typeof AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren
}

const AuthenticatedChampionshipsIdMatchesRouteChildren: AuthenticatedChampionshipsIdMatchesRouteChildren =
  {
    AuthenticatedChampionshipsIdMatchesMatchIdRoute:
      AuthenticatedChampionshipsIdMatchesMatchIdRouteWithChildren,
  }

const AuthenticatedChampionshipsIdMatchesRouteWithChildren =
  AuthenticatedChampionshipsIdMatchesRoute._addFileChildren(
    AuthenticatedChampionshipsIdMatchesRouteChildren,
  )

interface AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren {
  AuthenticatedChampionshipsIdTeamsTeamIdEditRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdEditRoute
  AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute
  AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute
  AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute
  AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute
  AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute
}

const AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren: AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren =
  {
    AuthenticatedChampionshipsIdTeamsTeamIdEditRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdEditRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdResponsiblesRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdRosterRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdStaffRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdIndexRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdAthletesAthleteIdRoute,
    AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdAthletesNewRoute,
  }

const AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren =
  AuthenticatedChampionshipsIdTeamsTeamIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdTeamsTeamIdRouteChildren,
  )

interface AuthenticatedChampionshipsIdTeamsRouteChildren {
  AuthenticatedChampionshipsIdTeamsTeamIdRoute: typeof AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren
  AuthenticatedChampionshipsIdTeamsNewRoute: typeof AuthenticatedChampionshipsIdTeamsNewRoute
  AuthenticatedChampionshipsIdTeamsIndexRoute: typeof AuthenticatedChampionshipsIdTeamsIndexRoute
}

const AuthenticatedChampionshipsIdTeamsRouteChildren: AuthenticatedChampionshipsIdTeamsRouteChildren =
  {
    AuthenticatedChampionshipsIdTeamsTeamIdRoute:
      AuthenticatedChampionshipsIdTeamsTeamIdRouteWithChildren,
    AuthenticatedChampionshipsIdTeamsNewRoute:
      AuthenticatedChampionshipsIdTeamsNewRoute,
    AuthenticatedChampionshipsIdTeamsIndexRoute:
      AuthenticatedChampionshipsIdTeamsIndexRoute,
  }

const AuthenticatedChampionshipsIdTeamsRouteWithChildren =
  AuthenticatedChampionshipsIdTeamsRoute._addFileChildren(
    AuthenticatedChampionshipsIdTeamsRouteChildren,
  )

interface AuthenticatedChampionshipsIdRouteChildren {
  AuthenticatedChampionshipsIdAthletesRoute: typeof AuthenticatedChampionshipsIdAthletesRoute
  AuthenticatedChampionshipsIdMatchesRoute: typeof AuthenticatedChampionshipsIdMatchesRouteWithChildren
  AuthenticatedChampionshipsIdStandingsRoute: typeof AuthenticatedChampionshipsIdStandingsRoute
  AuthenticatedChampionshipsIdStatsRoute: typeof AuthenticatedChampionshipsIdStatsRoute
  AuthenticatedChampionshipsIdTeamsRoute: typeof AuthenticatedChampionshipsIdTeamsRouteWithChildren
  AuthenticatedChampionshipsIdIndexRoute: typeof AuthenticatedChampionshipsIdIndexRoute
}

const AuthenticatedChampionshipsIdRouteChildren: AuthenticatedChampionshipsIdRouteChildren =
  {
    AuthenticatedChampionshipsIdAthletesRoute:
      AuthenticatedChampionshipsIdAthletesRoute,
    AuthenticatedChampionshipsIdMatchesRoute:
      AuthenticatedChampionshipsIdMatchesRouteWithChildren,
    AuthenticatedChampionshipsIdStandingsRoute:
      AuthenticatedChampionshipsIdStandingsRoute,
    AuthenticatedChampionshipsIdStatsRoute:
      AuthenticatedChampionshipsIdStatsRoute,
    AuthenticatedChampionshipsIdTeamsRoute:
      AuthenticatedChampionshipsIdTeamsRouteWithChildren,
    AuthenticatedChampionshipsIdIndexRoute:
      AuthenticatedChampionshipsIdIndexRoute,
  }

const AuthenticatedChampionshipsIdRouteWithChildren =
  AuthenticatedChampionshipsIdRoute._addFileChildren(
    AuthenticatedChampionshipsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrganizerRouteRoute: typeof AuthenticatedOrganizerRouteRouteWithChildren
  AuthenticatedChampionshipsIdRoute: typeof AuthenticatedChampionshipsIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrganizerRouteRoute:
    AuthenticatedOrganizerRouteRouteWithChildren,
  AuthenticatedChampionshipsIdRoute:
    AuthenticatedChampionshipsIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SystemAdminRouteRouteChildren {
  SystemAdminIndexRoute: typeof SystemAdminIndexRoute
}

const SystemAdminRouteRouteChildren: SystemAdminRouteRouteChildren = {
  SystemAdminIndexRoute: SystemAdminIndexRoute,
}

const SystemAdminRouteRouteWithChildren =
  SystemAdminRouteRoute._addFileChildren(SystemAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SystemAdminRouteRoute: SystemAdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CSlugRoute: CSlugRoute,
  TeamAccessTokenRoute: TeamAccessTokenRoute,
  TeamAccessSessionRoute: TeamAccessSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
