-- Phase 6 / F6-RF07: operational telemetry, health and runbook-backed alerts.

CREATE TABLE IF NOT EXISTS public.platform_operational_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  event_kind text NOT NULL,
  source text NOT NULL,
  severity text NOT NULL,
  code text NOT NULL,
  fingerprint text,
  route text,
  duration_ms integer,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT platform_operational_events_kind_check
    CHECK (
      event_kind IN (
        'client_error',
        'server_error',
        'rpc_failure',
        'auth_failure',
        'job_failure',
        'webhook_failure'
      )
    ),
  CONSTRAINT platform_operational_events_source_check
    CHECK (source IN ('client', 'server', 'rpc', 'auth', 'job', 'webhook')),
  CONSTRAINT platform_operational_events_severity_check
    CHECK (severity IN ('info', 'warning', 'error', 'critical')),
  CONSTRAINT platform_operational_events_code_check
    CHECK (length(code) BETWEEN 2 AND 100),
  CONSTRAINT platform_operational_events_fingerprint_check
    CHECK (fingerprint IS NULL OR length(fingerprint) BETWEEN 8 AND 128),
  CONSTRAINT platform_operational_events_route_check
    CHECK (route IS NULL OR length(route) BETWEEN 1 AND 200),
  CONSTRAINT platform_operational_events_duration_check
    CHECK (duration_ms IS NULL OR duration_ms BETWEEN 0 AND 600000)
);

CREATE INDEX IF NOT EXISTS platform_operational_events_occurred_idx
  ON public.platform_operational_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS platform_operational_events_kind_occurred_idx
  ON public.platform_operational_events (event_kind, occurred_at DESC);
CREATE INDEX IF NOT EXISTS platform_operational_events_severity_occurred_idx
  ON public.platform_operational_events (severity, occurred_at DESC);
CREATE INDEX IF NOT EXISTS platform_operational_events_actor_occurred_idx
  ON public.platform_operational_events (actor_user_id, occurred_at DESC)
  WHERE actor_user_id IS NOT NULL;

ALTER TABLE public.platform_operational_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.platform_operational_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.platform_operational_events TO service_role;

CREATE OR REPLACE FUNCTION public.record_my_client_error(
  p_code text,
  p_fingerprint text,
  p_route text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  clean_code text := btrim(COALESCE(p_code, ''));
  clean_fingerprint text := lower(btrim(COALESCE(p_fingerprint, '')));
  clean_route text := btrim(COALESCE(p_route, ''));
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING
      ERRCODE = '42501',
      MESSAGE = 'operational_event:authentication_required';
  END IF;
  IF clean_code !~ '^[A-Za-z][A-Za-z0-9_.:-]{1,99}$' THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'operational_event:invalid_code';
  END IF;
  IF clean_fingerprint !~ '^[0-9a-f]{8,64}$' THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'operational_event:invalid_fingerprint';
  END IF;
  IF length(clean_route) NOT BETWEEN 1 AND 200
    OR left(clean_route, 1) <> '/'
    OR clean_route LIKE '%?%'
    OR clean_route LIKE '%#%'
  THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'operational_event:invalid_route';
  END IF;
  IF (
    SELECT count(*)
    FROM public.platform_operational_events event
    WHERE event.actor_user_id = auth.uid()
      AND event.source = 'client'
      AND event.occurred_at >= now() - interval '1 hour'
  ) >= 20 THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'operational_event:rate_limited';
  END IF;

  INSERT INTO public.platform_operational_events (
    actor_user_id,
    event_kind,
    source,
    severity,
    code,
    fingerprint,
    route
  ) VALUES (
    auth.uid(),
    'client_error',
    'client',
    'error',
    clean_code,
    clean_fingerprint,
    clean_route
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_platform_operational_status()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, auth, storage
AS $$
DECLARE
  database_bytes bigint;
  storage_bytes bigint;
  storage_objects bigint;
  auth_users bigint;
  email_configurations bigint;
  billing_connections bigint;
  transaction_commits bigint;
  transaction_rollbacks bigint;
  deadlocks bigint;
  stats_reset_at timestamptz;
  events_24h bigint;
  errors_24h bigint;
  critical_24h bigint;
  rpc_failures_24h bigint;
  auth_failures_24h bigint;
  job_failures_24h bigint;
  webhook_failures_24h bigint;
  average_duration_ms numeric;
  p95_duration_ms numeric;
  recent_events jsonb;
  alerts jsonb;
BEGIN
  PERFORM public.assert_system_admin();

  SELECT pg_database_size(current_database()) INTO database_bytes;

  SELECT
    count(*),
    COALESCE(sum(
      CASE
        WHEN object.metadata->>'size' ~ '^[0-9]+$'
        THEN (object.metadata->>'size')::bigint
        ELSE 0
      END
    ), 0)
  INTO storage_objects, storage_bytes
  FROM storage.objects object;

  SELECT count(*) INTO auth_users FROM auth.users;
  SELECT count(*) INTO email_configurations
  FROM public.notification_delivery_settings settings
  WHERE settings.email_enabled
    AND settings.smtp_validated_at IS NOT NULL;
  SELECT count(*) INTO billing_connections
  FROM public.organization_subscriptions subscription
  WHERE subscription.provider IS NOT NULL
    AND subscription.provider_subscription_id IS NOT NULL;

  SELECT
    COALESCE(stats.xact_commit, 0),
    COALESCE(stats.xact_rollback, 0),
    COALESCE(stats.deadlocks, 0),
    stats.stats_reset
  INTO transaction_commits, transaction_rollbacks, deadlocks, stats_reset_at
  FROM pg_stat_database stats
  WHERE stats.datname = current_database();

  SELECT
    count(*),
    count(*) FILTER (WHERE event.severity IN ('error', 'critical')),
    count(*) FILTER (WHERE event.severity = 'critical'),
    count(*) FILTER (WHERE event.event_kind = 'rpc_failure'),
    count(*) FILTER (WHERE event.event_kind = 'auth_failure'),
    count(*) FILTER (WHERE event.event_kind = 'job_failure'),
    count(*) FILTER (WHERE event.event_kind = 'webhook_failure'),
    round(avg(event.duration_ms)::numeric, 2),
    round(
      percentile_cont(0.95) WITHIN GROUP (ORDER BY event.duration_ms)::numeric,
      2
    )
  INTO
    events_24h,
    errors_24h,
    critical_24h,
    rpc_failures_24h,
    auth_failures_24h,
    job_failures_24h,
    webhook_failures_24h,
    average_duration_ms,
    p95_duration_ms
  FROM public.platform_operational_events event
  WHERE event.occurred_at >= now() - interval '24 hours';

  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', recent.id,
      'event_kind', recent.event_kind,
      'source', recent.source,
      'severity', recent.severity,
      'code', recent.code,
      'fingerprint', recent.fingerprint,
      'route', recent.route,
      'duration_ms', recent.duration_ms,
      'occurred_at', recent.occurred_at
    )
    ORDER BY recent.occurred_at DESC, recent.id DESC
  ), '[]'::jsonb)
  INTO recent_events
  FROM (
    SELECT event.*
    FROM public.platform_operational_events event
    ORDER BY event.occurred_at DESC, event.id DESC
    LIMIT 20
  ) recent;

  SELECT COALESCE(jsonb_agg(candidate.alert ORDER BY candidate.priority), '[]'::jsonb)
  INTO alerts
  FROM (
    SELECT
      1 AS priority,
      jsonb_build_object(
        'id', 'critical-events',
        'severity', 'critical',
        'title', 'Eventos críticos nas últimas 24 horas',
        'description', critical_24h || ' evento(s) exigem análise imediata.',
        'runbook_id', 'incident-triage'
      ) AS alert
    WHERE critical_24h > 0
    UNION ALL
    SELECT
      2,
      jsonb_build_object(
        'id', 'operational-errors',
        'severity', 'warning',
        'title', 'Falhas operacionais nas últimas 24 horas',
        'description', errors_24h || ' erro(s) foram registrados.',
        'runbook_id', 'incident-triage'
      )
    WHERE errors_24h > 0
    UNION ALL
    SELECT
      3,
      jsonb_build_object(
        'id', 'database-deadlocks',
        'severity', 'warning',
        'title', 'Deadlocks acumulados no banco',
        'description', deadlocks || ' deadlock(s) desde o reset das estatísticas.',
        'runbook_id', 'database-contention'
      )
    WHERE deadlocks > 0
    UNION ALL
    SELECT
      4,
      jsonb_build_object(
        'id', 'backup-policy-pending',
        'severity', 'warning',
        'title', 'RPO, RTO e restauração aguardam decisão',
        'description', 'Não há meta aprovada nem evidência registrada de restauração em ambiente descartável.',
        'runbook_id', 'backup-restore-validation'
      )
  ) candidate;

  RETURN jsonb_build_object(
    'generated_at', now(),
    'health', jsonb_build_array(
      jsonb_build_object(
        'dependency', 'database',
        'status', 'operational',
        'detail', 'Consulta operacional respondida pelo PostgreSQL.'
      ),
      jsonb_build_object(
        'dependency', 'auth',
        'status', 'operational',
        'detail', auth_users || ' identidade(s) acessíveis no catálogo Auth.'
      ),
      jsonb_build_object(
        'dependency', 'storage',
        'status', 'operational',
        'detail', storage_objects || ' objeto(s) acessíveis no catálogo Storage.'
      ),
      jsonb_build_object(
        'dependency', 'email',
        'status', CASE WHEN email_configurations > 0 THEN 'configured' ELSE 'not_configured' END,
        'detail', email_configurations || ' organização(ões) com SMTP validado.'
      ),
      jsonb_build_object(
        'dependency', 'billing',
        'status', CASE WHEN billing_connections > 0 THEN 'configured' ELSE 'not_configured' END,
        'detail', billing_connections || ' assinatura(s) vinculadas a provedor.'
      ),
      jsonb_build_object(
        'dependency', 'client_error_reporting',
        'status', CASE WHEN events_24h > 0 THEN 'collecting' ELSE 'ready_no_recent_events' END,
        'detail', events_24h || ' evento(s) operacional(is) nas últimas 24 horas.'
      )
    ),
    'metrics_24h', jsonb_build_object(
      'events', events_24h,
      'errors', errors_24h,
      'critical', critical_24h,
      'rpc_failures', rpc_failures_24h,
      'auth_failures', auth_failures_24h,
      'job_failures', job_failures_24h,
      'webhook_failures', webhook_failures_24h,
      'average_duration_ms', average_duration_ms,
      'p95_duration_ms', p95_duration_ms
    ),
    'database_activity', jsonb_build_object(
      'commits', transaction_commits,
      'rollbacks', transaction_rollbacks,
      'deadlocks', deadlocks,
      'stats_reset_at', stats_reset_at
    ),
    'resource_usage', jsonb_build_object(
      'database_bytes', database_bytes,
      'storage_bytes', storage_bytes,
      'storage_objects', storage_objects,
      'email_cost_tracking', 'unavailable_without_provider_integration',
      'billing_cost_tracking', 'unavailable_without_provider_integration'
    ),
    'alerts', alerts,
    'recent_events', recent_events,
    'runbooks', jsonb_build_array(
      jsonb_build_object(
        'id', 'incident-triage',
        'title', 'Triagem de incidente',
        'steps', jsonb_build_array(
          'Confirmar horário, rota, código e fingerprint do evento.',
          'Correlacionar com logs do deploy e alterações recentes.',
          'Conter o impacto sem apagar evidências.',
          'Registrar causa raiz, correção e validação.'
        )
      ),
      jsonb_build_object(
        'id', 'database-contention',
        'title', 'Contenção e deadlocks',
        'steps', jsonb_build_array(
          'Identificar consultas e transações concorrentes no provedor.',
          'Revisar ordem de locks e duração das transações.',
          'Validar a correção com concorrência controlada.',
          'Acompanhar o contador após o próximo reset de estatísticas.'
        )
      ),
      jsonb_build_object(
        'id', 'backup-restore-validation',
        'title', 'Validação de backup e restauração',
        'steps', jsonb_build_array(
          'Definir e aprovar metas de RPO e RTO.',
          'Criar ambiente descartável isolado da produção.',
          'Restaurar o backup mais recente e medir os tempos.',
          'Validar integridade, RLS e amostras funcionais.',
          'Registrar evidências, lacunas e data do próximo teste.'
        )
      )
    ),
    'continuity', jsonb_build_object(
      'rpo', 'pending_approval',
      'rto', 'pending_approval',
      'restore_test', 'not_recorded'
    )
  );
END;
$$;

REVOKE ALL ON FUNCTION public.record_my_client_error(text,text,text)
  FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.get_platform_operational_status()
  FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.record_my_client_error(text,text,text)
  TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_platform_operational_status()
  TO authenticated;

